### ISSUE TITLE
Suggestions for panel names and contents on 1E

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#263]
1) Command receiver gets "Software Commands" and "Number of Commands" (see previous issue saying that it is missing).  Is it possible to make this a bit less obvious?  Somehow requiring another click to get to?  At least for SoftwareCommands.  Maybe it could be called ICR Diagnostics or something".

2) Under command receiver, MUX should be labelled "Sensor Power"

3) Delete "computer hardware" panel and put i2c under their respective slaves (Battery, MPPT (not PSU), RF->ICR

4) Replace "computer software" with "Satellite State".  Software Commands has moved to ICR.  Move Spin to MPPT (since it is found through MPPT)

**Comment by ac2cz** [comment]
1) Command Receiver updated to have Num of Commands and Diagnostic (software commands)
2) MUX called Sensor Power on the GUI

For 3) and 4), let's discuss how much we want this to follow the previous layout for Fox.  We can move all the things around, but then we will have 1 satellite with everything in a different place.  Another approach would be to change the layout for IHU/Non IHU items for all sats.

**Comment by ac2cz** [comment]
I want to close this out if possible.  Do you still want me to delete Computer Hardware and name Computer Software "Spacecraft State"?  I can put the I2C statues in the other panels, but where to put the Computer Temp, Ground Resets and Hard Error?  These are going to end up back in "Spacecraft State" and it will be too large again.  Which was why I split "Computer" in the first place.

So assigned back to Burns for the final design and then I will implement.

**Comment by burnsfisher** [comment]
Don't bother.  I think it is ok.  I can at least see the logic to it :-)
