### ISSUE TITLE
FM Satellites have only a header on -X,-Y,-Z, and +Z panels

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#264]
This is on V1.05j.  I have not received any data from any of these, but the fact the +X and +Y look reasonable makes me think there is a problem with the others.

Actually, the RadFxSat (1) tab is only missing the -panels.  All the + panels are ok.
![screenshot 2017-06-29 18 26 16](https://user-images.githubusercontent.com/2413372/27712878-faa185c4-5cf6-11e7-893a-67ea69f5f438.png)

**Comment by ac2cz** [comment]
This is a layout issue. The new layout files will be included in 1.05j

**Comment by ac2cz** [comment]
Closed as duplicate
