### ISSUE TITLE
Bare bones Windows 7 is missing MSVCR100.dll

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#287]
The Visual C 2010 redistributable is generally missing from Windows.   I suggest that you include it to be installed by a first-time user.

**Comment by ac2cz** [comment]
I have changed the launcher for 1.06h onwards and it may not need this.

**Comment by ac2cz** [comment]
This is now clearly documented in the manual.  I'm not going to bundle with FoxTelem so I am closing this.
