### ISSUE TITLE
Odd Fox-1E High/Low behavior

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#291]
I have been running Fox-1e for several hours with FoxTelem collecting data. There are very few errors in the data and very few (if any) packets missed.  I walked away for some time and when I came back, I noticed that on the health screen, the most recent realtime data was at time 52/4800 (about) but that the most recent min and max telemetry was in the vicinity of 52/2500.  Those times are not exact.  I watched for a while to be sure that we were still getting data, and I saw frames ticking up, but payloads not so much.  I did see a new realtime telemetry come in.  After a couple minutes, the min/max telemetry updated.  On a hunch I looked at the WOD screen and the most recent WOD data was very close to the current time and the time of the min/max.  

Hypothesis:  FoxTelem can get into a state where, if a high/low frame has no new WODs to save, it also does not save the high/low data in that same packet.  

I have not been able to reproduce this and, of course, it could be that High/Low frames were simply not received by coincidence.

This is 1.05o with Fox flight software X5.4k (which is the same as 'j' except with a few more umbilical commands added.

**Comment by ac2cz** [comment]
I don't know how to trouble shoot this.  Should I add some more debug information?  Try running with Debug Frames turned on and the log file visible for a start.  That may show more of what is going on.

**Comment by ac2cz** [comment]
Also, see #271 as this could be the same issue.

**Comment by burnsfisher** [comment]
Are you suggesting leaving the log file turned on too then? 

BTW, I realized re-reading the initial note that I really screwed up the description due to typos.  I fixed it up.  To me,  this does not seem so obviously related to #271 (especially after I fixed the description) because the Frames were getting decoded at the right rate, and realtime data also seemed ok.  However, no min/max data had been received for several thousand seconds.

Suggestion:  For debugging, add a ring buffer for the last couple of minutes of decoded frames, and some code to notice whether the last received min is more than, say, 10 minutes behind the last received realtime data.  The problem with logs is that if I leave the system running, I might not notice FoxTelem for hours and could easily miss this case.  Automatically detecting it would be better.

That said, I'm not sure I could call this CRITICAL.

**Comment by ac2cz** [comment]
This is likely related to #325

**Comment by ac2cz** [comment]
I believe this is no longer an issue in 1.06g given the extensive testing we did for dropped frames and the Doppler fixes.  Please test with the RTL and confirm it is not an issue.

**Comment by burnsfisher** [comment]
I have not seen this issue lately.
