### ISSUE TITLE
When you switch log directories, frames counter is unchanged

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#293]
Ditto downloading from the server.

**Comment by ac2cz** [comment]
We need to decide if this is a real feature that will be in the live release.  If so, then the value needs to be saved in a file in the LOG DIR.  Right now it is saved in FoxTelem.properties in the HOME DIR.

**Comment by burnsfisher** [comment]
Understood.  It would not be a bad thing if it were just zeroed on every
restart.

**Comment by ac2cz** [comment]
Fixed in 1.05p
