### ISSUE TITLE
V1.05o odd display for Cell A+B voltage

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#296]
See the screenshot.  There are letter rather than numbers in the display.
![screenshot 2017-09-04 08 53 27](https://user-images.githubusercontent.com/2413372/30027391-c82cab46-914e-11e7-8d6c-bb18f5b34ba9.png)

Again, I see this on the 1E engineering model.  No reason to think it is not there on others.

**Comment by ac2cz** [comment]
This is fixed in v1.05p
