### ISSUE TITLE
WOD Stored label and calculation is wrong

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#297]
For Fox-1E the computer software pane, "WOD Stored (000s)" label is incorrect as is the calculation done for non-raw values.  In fact the raw value is the actual value divided by 4, so the non-raw version should be 100 rather than 25.0 in the current case.  I'm not sure if you want to use a different label for raw and processed, or if you just want to say "WOD Stored" and have it only correct for processed.

**Comment by ac2cz** [comment]
Currently WOD Stored has no conversion.  It is just displayed as though it is an integer value.  v1.05p includes new conversion to multiply by 4.

**Comment by burnsfisher** [comment]
The value displayed is correct.  The label should remove (000s).
