### ISSUE TITLE
Fox1E WOD RAD records are not correctly written to the Server DB

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#298]
The Lat, Long and Height values are written as NULL.  This causes an issue when the data is downloaded to FoxTelem.  You can reproduce by showing "raw values" on any tab.

**Comment by ac2cz** [comment]
Do the RAD WOD records need to have position data?  FoxTelem does not currently calculate the position.  For some reason the server creates the three fields for WOD RAD data, but they are not populated.

**Comment by burnsfisher** [comment]
Where would you get the position data from?  Certainly Brian wants to know the position of the satellite for each record collected, but that can be calculated from the time and appropriate keps.   I guess if there were a way to do it, it would be nice to have that info in the server, but only if it is pretty reliable.

**Comment by ac2cz** [comment]
I am calculating the position of Fox-1E using the Java port of Predict.  The calculated values seem to agree with SatPC32.  Right now I store the values with the WOD values as an experiment.  There is no reason I can not store them will all records though.  In fact I am going to calculate the satellite position for each frame anyway, instead of calling SatPC32 over DDE.  I'll leave DDE as an option, but I think calculating the position will be more stable than using DDE.

I need to finish the implementation and then this will be in 1.05p

**Comment by ac2cz** [comment]
I will address this in two ways.  First we should be able to handle a NULL in the received data from the server.  If we have a NULL then we will assume the value is NO_POSITION_DATA.

Secondly we should be ignoring the position data when the records are received at the server. We do not know how good the calculation is at the ground station.  The server should be recalculating the position and storing it. 

Thirdly, we will store position data for the RAD WOD records locally so that analysis can be performed on local data.

**Comment by ac2cz** [comment]
V1.05p will include a fix that prevents the crash.  The server will be updated in a separate release.

**Comment by ac2cz** [comment]
In 1.06b this is no longer an issue.  Data downloads fine.
