### ISSUE TITLE
Fox-1E RF temp formula needs updating

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#303]
The Fox-1E RxTx board uses a TMP36 temperature sensor rather than the thermistor used previously.  This has a nice linear output.  25c = 750mv and 10mv change per degree C from -40C to +125C (!).  This is also using the IHU A/D so that calibration of voltage to raw value needs to be used as well.

**Comment by ac2cz** [comment]
I will make this a new conversion.  Do we have this sensor in other positions with the same configuration, or is this going to be a conversion just for FOX1E_TXRX_TEMP?

**Comment by ac2cz** [comment]
I will implement this with the following conversion, correct me if I have it wrong.
Firstly we get the voltage:
v = raw * 3.0/4096

Then we use the fact that we have a straight line equation for the temperature, which crosses the axis at v = 500 and if we need 10mV for 1C change the has slope 0.1.  So with V in mV, T = 0.1*v - 50 

Or in Volts, T = 100*V-50

**Comment by ac2cz** [comment]
New conversion in v1.05p

**Comment by burnsfisher** [comment]
This also uses the IHU A/D converter, so you should be using that same calibration table--the IHU Vbatt table--to get the voltage.

In this table do you have values that give you close to 3V for a reading of 4095?  I'm asking because 4095 actually equals 6V for Vbatt, right?  There is a 50/50 voltage divider.
