### ISSUE TITLE
VBatt current zero point needs to be calibrated for Fox1E in EM testing

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#306]
This is a calibration point.  For Fox-1A it is set to -1.839.  You can see the value on the spacecraft settings screen. 

Burns or Eric to determine this value.

**Comment by burnsfisher** [comment]
Well that is confusing.  Not a problem, but just FYI, I changed the value in the spacecraft settings and suddenly the current displayed on health jumped from 18ma or so to 2000 or so.  Then I changed it back and healthscreen remained unchanged.  Finally I restarted FoxTelem and all was well.  So it appears that changing that value on the spacecraft screen has some effect, but not the "right" effect until you restart.  I'll think about how to get the right value for you.

**Comment by burnsfisher** [comment]
Assigned back to you with the correct ADC count for the EM.

**Comment by burnsfisher** [comment]
The offset value is very touchy.  For example, the default offset of 1.839 is yielding -2 ma or so, while my proposed 1.8344 gives +3ma or so for the same value.  So in the end, I don't think we can measure it ALL that carefully, especially when it comes to the flight model.  I'll lower the priority of this since the default value is not really bad.

**Comment by ac2cz** [comment]
Burns commented on a way to calibrate this:
I have accidentally found a way to calibrate the 0 current battery value.

1) Charge the battery as full as possible using the battery tender or MPPT.  About 4.15V on the EM. 

2) Now power the EM stack from the wall wart.  Note that the wall wart is about 4.5V, but that it goes through a Shottky diode to get to Vbatt on the s/c bus, and that does through yet another diode (D12) to get to the battery.  Vbatt is now reading 4.18.  Not enough to go back through D12 to charge the battery.  Voila!  No battery current. 

The raw reading in this case varies a bit in the vicinity of 1865.  The offset in FoxTelem works pretty well if it is -1.834.

The center point all depends on the resistors setting the offset point in the current amp on the battery board, so I don't know how close this will be for other battery boards.

**Comment by burnsfisher** [comment]
For 1E we may never have the chance to do this since it requires the flight battery card to be available on the breakout board.  The battery board has had several issues that push out its time frame, so I may never get to see it on a breakout board.

**Comment by burnsfisher** [comment]
Confirmed:  I will not have the battery board to put on the BoB, so we'll have just just hope it matches the EM

**Comment by ac2cz** [comment]
I re-read this thread and it seems that -1.834 is perhaps a better default than -1.839. So I have updated this.  Re-assing to Burns for final agreement.  We can change this after launch or even on a single install as it is in the spacecraft config file.

**Comment by burnsfisher** [comment]
The battery card had a lot of issues and I never actually got it before it
was assembled into the stack, so I could not do this calibration.  Bob
tried to, but he does not have the appropriate hardware.  We may just have
to hope that the default is good enough.

**Comment by burnsfisher** [comment]
Battery current seems sensible on the flight spare (but with the EM battery board).  That's the best we can do unless it reads nutso on the flight unit after that is assembled.
