### ISSUE TITLE
Crash of queueing/upload task

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#312]
1.05p:

I came in today and noticed a dialog box saying that the queue could not be erased (?).  I'm enclosing a picture.  Also, based on the fact that there seemed to be about 9000 packets in the queue, that would be 12-ish hours, and the last log file is older than that, so I am sending the log file as well.  I did not see anything obvious, but it's hard to search not knowing what you are looking for. 

After I dismissed the dialog box, the queued packets started counting down; I assume they were being sent.  I stopped FoxTelem to keep the log from getting any longer and then took the log file.

Now I have started up FoxTelem again, and it seems to be hanging at 80% with the "Loading Logged Data" dialog.  The log shows that the last thing happening is Loading rawPSKframes.log.  Maybe I am not waiting long enough.

**Comment by burnsfisher** [comment]
![screenshot 2017-09-25 15 28 57](https://user-images.githubusercontent.com/2413372/30827420-0c1a22ec-a208-11e7-9922-78790af73bc7.png)

Here is the screenshot.

**Comment by burnsfisher** [comment]
Here is the log file.
[FoxTelemDecoder20170925.log](https://github.com/ac2cz/FoxTelem/files/1330660/FoxTelemDecoder20170925.log)

**Comment by burnsfisher** [comment]
I deleted rawPSKframes as instructed by the dialog box, and FoxTelem started normally.

**Comment by ac2cz** [comment]
Burns, was this when you deleted the payloads, or when FoxTelem was running on its own?

**Comment by burnsfisher** [comment]
FoxTelem was running on its own.

**Comment by burnsfisher** [comment]
To clarify:  I walked in and saw the error dialog box after it had been running on its own for a while.  After I tried to restart it and it hung at 80%, only then did I delete the payload file.

**Comment by ac2cz** [comment]
Fixed in 1.05q

**Comment by burnsfisher** [comment]
Have not seen the problem again even with the fast uploads I am doing on the 1E engineering model.
