### ISSUE TITLE
Missing Packets in 1E

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#325]
I have frequently noticed missing packets even though the receiver and transmitter are close, the level seems ok, and on the non-missing packets, there are seldom any corrections or erasures.

I finally extracted the log and did some checking and discovered that yes, there are missing packets.  I don't know whether FoxTelem is missing them, or the satellite is not sending them (or sending them somehow broken).  I'm hoping that you can look at the log and see if there is enough info to tell.
Here is what I am attaching.  First, we have "type.pdf".  This is a spreadsheet  showing the lines from the log that have "TYPE:" in them.  Luckily you can see the time and the packet type in the same line.  I added a column (K) which is the time between this packet and the previous one.  And I added "J" which in the ones I looked at shows what the missing packet types are.  The order should be

1 0 0 1 0 0 1 2 0 1 0 0

Note that sometimes we are missing one packet and sometimes two.

I'm also including the complete text of the log file that covers the time of the spreadsheet.

I will also look to see if there is something fishy going on with the flight software, but if you can see anything in the log either relating to FoxTelem or what the satellite is sending, I'd appreciate it if you could tell me. 

I'm going to mark this critical because if there is a flight software problem I need to know soon in order to fix it.  If it is really a FoxTelem problem it might only be a high.

[FoxTelemLog.txt](https://github.com/ac2cz/FoxTelem/files/1357383/FoxTelemLog.txt)
[FoxTelemLogSpreadSheet.pdf](https://github.com/ac2cz/FoxTelem/files/1357386/FoxTelemLogSpreadSheet.pdf)

**Comment by ac2cz** [comment]
Investigation has shown that we loose frames when 1 or more bits are dropped.  It's unclear where and when the bits are dropped, but it seems likely that Windows audio is the culprit.  Running an FCD on a USB hub seemed to increase the problem, for example.

We attempt to address this by inserting the missed bits.  We guess at the position by checking the erasures when bits are inserted.  There are too many potential bit positions for us to run the full RS decode for each attempt.

This fixes some of the situations but not all.  More investigation needed.

**Comment by burnsfisher** [comment]
Not sure if you want this open but it still happens on 1.06e.  Here is a log file.  The very last packet decoded in it is the first packet of a safe mode beacon.  The second packet was not decoded.  I don't know what I'm seeing in the log, but if it is useful to you, go at it!

[FoxTelemDecoder20171226.log](https://github.com/ac2cz/FoxTelem/files/1587833/FoxTelemDecoder20171226.log)

**Comment by ac2cz** [comment]
Extensive investigation at both the IHU and FoxTelem end has concluded that these bits are dropped by Windows Audio.  They are dropped even if the FCD is recorded directly into Audacity.  The bits are not dropped if an RTL dongle is used, which does not use Windows Audio. It reads bytes directly through its USB interface, which is not a USB sound card.

Audacity was slightly better if MME was used as the Audio interface, but not dramatically so.  The FCD was worse if plugged into a hub.  

Assigning back to Burns for the final comments, but I would suggest that this is closed.  Fix Dropped Bits should be enabled if you are using Windows Audio to try to compensate.

**Comment by ac2cz** [comment]
Note that we do have one other situation where packets are missed, but that is tracked by another CRITICAL issue: #415.  I suggest we close this and leave that concrete case open.  They are the only frames missed on the RTL.
