### ISSUE TITLE
Airpy shows error messages at boot if device already used by another program

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#337]
Reported by Alan:
Normally, I run one version with FCD+ directly, and another with the Airspy feeding SDR# and then Foxtelem through a VAC.  Works fine, and there is some modest benefit in the diversity processing.  As a test, I cleaned out those directories completely, and installed the new version in both, configured as before.  I am using the old method of running two versions, wanting to take it a step at a time.  However, when I start the second version of FoxTelem, either order, I get this:
![image](https://user-images.githubusercontent.com/14824793/31360849-4a7e1b26-ad1e-11e7-911c-741bb0e01ec6.png)
![image](https://user-images.githubusercontent.com/14824793/31360851-4e98445c-ad1e-11e7-8ab0-436e43bdce38.png)
Note that neither version is looking at the Airspy. 

 

If I start SDR# with either running, I get an equivalent message about Airspy not being available.  Is FoxTelem keeping Airspy hooked as part of the device enumeration process?

**Comment by ac2cz** [comment]
Another bit of data.  Alan had 1.05p running with FCD+, only, and the last release version of FoxTelem with Airspy.  He did not see any conflict messages between 1.05p and SDR#.

**Comment by ac2cz** [comment]
Fixed in v1.05s I hope.  Alan needs to test.  I don't have the device.

**Comment by WA4SCA** [comment]
Verified that the error message is now suppressed.  However, unlike version 1.04f and earlier versions of 1.05, FoxTelem still grabs the Airspy if started first even if Airspy is not the selected source.  This looks like something which should remain open, but at low priority until an Airspy is available for testing.

**Comment by ac2cz** [comment]
Ok, that is a problem.  I changed the way this works when I implemented the RTL.  I wanted it to find all the USB devices and only show the ones that are available.  But I don't think I can do that easily without opening them.  I know from past experience that once opened it is hard to really close them without exiting the application.  Windows has the same issue with files sometimes.  You close the document but Windows tells you it is in use until you exit the application that had opened it.

So I think I will adopt the approach that SDR# uses.  I will list the Airspy and RTL every time the list is opened.  If you click one it tries to open it.  Never before.  They will be listed even if you don't own one.  

Note that the FCD is treated as a sound card, so it will continue to be listed the old way, but I may migrate that to this approach in the future. We have the same issue with the FCD as I remember.

**Comment by ac2cz** [comment]
I am going to pull the AirSpy support from 1.05 release.  It's possible that I will release a patch for those interested when I get my replacement and can debug this further. For now I will remove it from the code and then move any open issues too release 1.06.

**Comment by WA4SCA** [comment]
Concur.

73s,

Alan
WA4SCA
