### ISSUE TITLE
1.05t Does Not Work On Mac

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#349]
The ZIP file has an elf file, a jar file and the spacecraft folder.  Is that correct?  The Elf file did nothing obvious on the Mac.  The Jar file required me to right click/open rather than double click.  It then crashed with a null pointer.  Trying to shut it down ended up with a null pointer also.  The only way to get rid of it was ps -A | grep -i foxtelem to get the PID and the kill the pid from the terminal.
<img width="864" alt="screen shot 2017-10-14 at 8 29 38 pm" src="https://user-images.githubusercontent.com/2413372/31580504-7267ab66-b11f-11e7-9c50-a17f01e75417.png">
<img width="966" alt="screen shot 2017-10-14 at 8 29 15 pm" src="https://user-images.githubusercontent.com/2413372/31580505-74566d86-b11f-11e7-9ac9-ebf95837140d.png">

**Comment by burnsfisher** [comment]
The new 1.05t seems to work as long as I start it by double-clicking the jar file.  (Have not tried de-modulating.  Only downloading from the server).  A few exceptions:

1:  I get error messages trying to download Fox C, D, and E.  Something about compression not working.  Then it continues.  Should just ignore them.

2:  If you double click on the jar file, the icon in the dock is Java, not FoxTelem.  And you can't lock it there as a shortcut.

3.  If you actually try to run the shell script from a terminal, you get a message similar to the one I reported for Ubuntu Linux.

**Comment by ac2cz** [comment]
The shell script run issue will be addressed when fixing the linux install/launch. #351 

I can't fix the icon issue unless we create another Mac launcher and I don't know how to do that.

I had implemented a change for the error messages, as that is not Mac specific.    So given the original error is fixed, the script issue will be fixed separately and the icon issue will not be fixed, this can be closed with the compression error surpressed in 1.05u

**Comment by ac2cz** [comment]
Assigned to Burns to close

**Comment by ac2cz** [comment]
Burns, let me know if we can close this, otherwise I will move it to Release 1.06

**Comment by burnsfisher** [comment]
Sorry, I won't be able to check this for a week--just about to leave for
the Symposium.

**Comment by ac2cz** [comment]
Any remaining Mac issues will be addressed in 1.06
