### ISSUE TITLE
5w on Mac gives errors trying to download data from the server

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#363]
I tried to download the data from the test server to my Mac.  For RadFxSat, 1Cliff, and 1D (I think) I got an error saying it could not write to my directory.  It got 1E and then complained again without mentioning a specific satellite.  After I dismissed the errors, it appears that it got the data ok.

**Comment by burnsfisher** [comment]
Not wildly important.  I can't try on Windows right now.  Probably worth checking.

**Comment by ac2cz** [comment]
Hmm, I fixed this bug, but I see it is there on Windows too.  I do not get the error when downloading from the real server, just from the test server.  This won't be fixed in 1.05, but I might fix it in the Fox-1E release.  For now remove the spacecraft that you don't want to download.

**Comment by burnsfisher** [comment]
Ok.  It is entirely possible to work around it in any case.  Thanks...

**Comment by ac2cz** [comment]
Fixed in 1.06b

**Comment by burnsfisher** [comment]
Seem ok even on the test server.
