### ISSUE TITLE
Please make bit-encoded fields in WOD data hex, not decimal

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#365]
It's nearly impossible to scan the WOD to find diagnostic info.  It would be nice if they were all translated like the expanded realtime diagnostics are, but if not, that's ok.  Just putting them in hex means I can scan the last two digits for the type field.

It would be good for IHU Hard Error and Soft Error too, but not so critical.

**Comment by burnsfisher** [comment]
This relates to all satellites, but I labelled it 1E because that is where I need it relatively quickly.

**Comment by ac2cz** [comment]
Please give me some more details on what you mean.  The WOD Diagnostic info is stored and displayed in the same way as the Real Time info.  What needs to be "translated and expanded"?

![image](https://user-images.githubusercontent.com/14824793/32702836-b030a202-c7ba-11e7-85e8-d8a465db2118.png)

**Comment by burnsfisher** [comment]
Hmm.  Maybe I did not look at the right thing somehow.   I'm in CA right
now for the launch.  I'll see (after dinner) if I can pull some stuff down
from the test server to try to replicate what I was talking about

**Comment by burnsfisher** [comment]
Ok, I see.  I did not occur to me to get the WOD charts the same way as the
realtime charts.  <duh>.  So I was really talking about the data down at
the bottom of the main WOD window that you can pull up to see everything
for each second.  Not so important with the other charts.  Thanks!
