### ISSUE TITLE
HighSpeed Frames are again unnecessarily held in the queue until the pass was finished

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#370]
Spotted by Alan on 11/13 HS pass.

**Comment by ac2cz** [comment]
Has this been seen since?  Drew saw it too, but most people have not reported it.  I think that it can also happen if the connection to the server times out and FoxTelem waits 5 mins.

**Comment by ac2cz** [comment]
Recent observations of High Speed pass shows that this seems to be fine and I will close out.

**Comment by WA4SCA** [comment]
This morning I was able to catch two passes where AO-92 came up in DUV, showing the standard Queued:1 on the FCDP+ system. Both times as soon as it switched to camera mode, the number of queued items incremented along with the frames until shortly after LOS, at which point the queue emptied quickly. The system using AF from the Airspy and SDR# behaved normally.

**Comment by ac2cz** [comment]
I would like to fix this (time permitting) but no data is lost, so I have downgraded to High from Critical.

**Comment by ac2cz** [comment]
The test case seems to be that we are already in faded for DUV, holding 1 record, and then we start high speed.

**Comment by ac2cz** [comment]
I can reproduce this.  And what is more, it seems to get stuck in DUV and not want to switch to HS when it is in "Faded"

**Comment by ac2cz** [comment]
Still an issue in 1.08h.

**Comment by ac2cz** [comment]
A while loop waited until all of the DUV frames were sent.  That is changed, but the logic is complex.  So now we hold 2 frames in this situation.  One DUV and one HS.  At the end of the pass both are sent once FADED expires.  The pass information is put on the DUV record regardless, which is misleading if it was held from the beginning of the pass, but the calculation for TCA is only based on the DUV records, so it feels OK.

**Comment by ac2cz** [comment]
"Fixed" in 1.08i
