### ISSUE TITLE
Science experiment board uptime issue

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#389]
The uptime for the selected experiment is not being decoded correctly, I don't believe.  The LEP experiment has only two bytes of time.  The other two have 3 bytes.  I think maybe you are treating them all as having 2 bytes?  Or 3?

**Comment by ac2cz** [comment]
If you have the layout for the telemetry then please supply it to me.  It is currently using the same layout at Fox-1A.

**Comment by ac2cz** [comment]
This is fixed in 1.06g

**Comment by ac2cz** [comment]
This should be fixed in 1.07b

**Comment by burnsfisher** [comment]
Now all 3 experiments have readings when they are shown.  I don't know if they are correct, but they are non-0 and seem reasonable.
