### ISSUE TITLE
Some problem with radiation telemetry

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#390]
When FoxTelem started, there was an error about being unable to load the RF filter.  As usual, I ignored it.  Some time later, I got the error you see on the screen.  I'm attaching a fairly long log file, but probably the thing of interest is only near the end.  Also a screen shot of the error.
![screenshot 2017-12-07 15 38 54](https://user-images.githubusercontent.com/2413372/33737906-ae953aa2-db65-11e7-8ca6-c72eefaa322a.png)
[FoxTelemDecoder20171207.log](https://github.com/ac2cz/FoxTelem/files/1540528/FoxTelemDecoder20171207.log)

**Comment by burnsfisher** [comment]
Pretty much the identical thing happened immediately after I restarted.  Here is a much shorter log.  I did not get the screen shot, but it looked similar.

[FoxTelemDecoder20171207 (2).log](https://github.com/ac2cz/FoxTelem/files/1540532/FoxTelemDecoder20171207.2.log)

**Comment by burnsfisher** [comment]
Tried again, this time I got that I could not fetch the LNA, and then no RF appeared at all.  Restarted (and power cycled the FCDPP) several times and finally got it to start with no message.  However, it then crashed with this again.

**Comment by burnsfisher** [comment]
I tried once again, this time with a totally new database and log directory.  Same thing.  So in other words I can not receive telemetry in transponder mode at all.  This is very high priority.

**Comment by ac2cz** [comment]
I'm not seeing that here. Can't reproduce. Did you install the new
spacecraft layouts or just the jar file?

**Comment by burnsfisher** [comment]
I installed everything.  A bit more that I just discovered.  If I turn the
experiment off so it gets all 0s for data, it is ok.  It's apparently only
when there is actual data that this happens.

**Comment by ac2cz** [comment]
Ok, that's very interesting. Let me investigate tonight. I might need a
recording to debug it.

Chris

**Comment by burnsfisher** [comment]
I just tried it with a non-existent experiment, so only the VUC data is
coming.  It still dies.

Would you like me to try to make some flight software that fakes sending
you some data?

**Comment by ac2cz** [comment]
A recording is better than changing the flight software. The first thing I
would do is record the fake data.

I can send you the setup details if you need it.  HDSDR at 192000 bandwidth
recorded straight from the FCFPP. Save RF. Works well usually.

Chris

**Comment by burnsfisher** [comment]
Ok, please send the setup.

**Comment by ac2cz** [comment]
Fixed in 1.06d

**Comment by burnsfisher** [comment]
Confirm that it is fixed.
