### ISSUE TITLE
FoxTelem conversions need to be provided for the new channels on the Fox-1E  TxRx

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#391]
We have already implemented the PA Current TxTemperature and RxTemperature.  These all use the IHU lookup table and conversion formulae.  They are implemented with new Conversion Codes and the logic in FoxFramePart.

We still require conversions for:
VGA
Fwd Power
Rev Power

**Comment by ac2cz** [comment]
For Forward Power out:
​y = 1.6707x^3 - 12.954x^2 + 37.706x - 14.388   where y = RF PWRout and x = Vfwd voltage

**Comment by ac2cz** [comment]
TX Ref Pwr:
x = (RAW VALUE/4096) x 2.5/0.758 = RAW VALUE x .0008051  
 where x = TX_FWD_RFLT, the RF detector output voltage 
 
Using the third degree polynomial curve-fitting equation from the graph, the resultant Ref Power (mW) can be calculated as:
y = 0.1921x3 + 14.663x2 + 11.56x - 1.8544                   where y = Ref Power (mW)

**Comment by ac2cz** [comment]
PA Current (mA) = {[(RAW VALUEAVG/4096) x 3.0] x CF} / 5 
  = (0.0001464 x RAW VALUE x CF)               where CF = the IHU's A/D non-linearity correction factor

**Comment by ac2cz** [comment]
VGA Control is just the 3V IHU sensor reading.  So this is grabbed from the lookup table for VBATT for the spacecraft.  Note that those values are twice the 3V reading, so they need to be halved.

**Comment by ac2cz** [comment]
Implemented in 1.06h

**Comment by burnsfisher** [comment]
These all seem very reasonable on the Flight model.
