### ISSUE TITLE
Display task crash

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#402]
Looking at the Fox-1E WOD for RSSI.  I hit the UTC button.  Since there is no T0 time, it did not change much.  Then I switched back to Uptime and got this crash.
![screenshot 2017-12-21 10 06 23](https://user-images.githubusercontent.com/2413372/34261429-1c5572a6-e637-11e7-8640-a5b99c8042e8.png)

**Comment by ac2cz** [comment]
I can reproduce this in 1.06.  This is likely the same as #403, as referenced in that issue

**Comment by ac2cz** [comment]
Fixed in 1.06e
