### ISSUE TITLE
RSSI WOD Graph

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#403]
The WOD graph always has labelled on the X-axis "Uptime" and "UTC" rather than uptime and resets even when uptime is selected. Worse, when you switch to "Next" display mode or "Range" display mode it asks for the UTC time, not the uptime.  I think this is tied in with the previous issue #402, when switching from UTC to uptime.

**Comment by ac2cz** [comment]
I can reproduce this in 1.06.

**Comment by ac2cz** [comment]
Fixed in 1.06e
