### ISSUE TITLE
Missing Label on WOD page

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#409]
1.06e:

I assume at the top right the number is "WOD Health Payloads Decoded" or something like that, but it is unlabelled.  Similarly, on the VU Rad WOD page, I'm guessing that number is really WOD Radition Payloads decoded.  It is labelled the same as the VU Rad (non-WOD) page, but the number is different.

**Comment by ac2cz** [comment]
Fixed in 1.06g

**Comment by burnsfisher** [comment]
Continues to be minor, but the VU Rad Wod right hand value is still labelled the same as that on VU Rad, but the number is different.  

I should add that maybe I don't understand why they are so different.  My Rad WOD value is 1515, while the Rad value is 6414.   For that matter, the health WOD is 1516, while the realtime health is 9699.  I don't think they should be wildly different if I understand what they mean.
