### ISSUE TITLE
RTL-SDR Gain Master Behavior

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#414]
I realize you don't support RTL-SDR, but I'll just log this for the future.

The "gain master" automatic value behaves oddly in several ways.  I'll record it all here.  Note:  I have not used manual at all; only the master.

1) If start FoxTelem and use RTL-SDR for the first time, it comes up in automatic, and at least with my setup, the gain was WAY too low.  Essentially nothing showed.  I set the gain master to 482 and it worked fine.  Then I set it back to automatic and it seemed to continue to work fine as though nothing had changed.

2) If I exit FoxTelem and restart it, the Gain Master setting appears not to have been saved; it shows as "Automatic" again.  However it may be that the gain value actually was saved because the gain is once again usable.  (Similar to (1) after switching back to automatic).

3) I'm pretty sure that if I leave FoxTelem running long enough with Gain Master set to a number, it will eventually change back to the label Automatic, although again it did not necessarily actually reduce the gain.

**Comment by ac2cz** [comment]
Duplicates #326 and addes some additional context.   I will close #326

**Comment by burnsfisher** [comment]
Just a note that this could be important for fox-in-a-box

**Comment by burnsfisher** [comment]
Oops.  Hit the wrong button, I think

**Comment by ac2cz** [comment]
Fixed in 1.06g

**Comment by burnsfisher** [comment]
Looks good.

**Comment by ac2cz** [comment]
Actually, I think there is a bug here.  It remembers the settings, but I am not sure it applies them.  If you go to another program and change them, or unplug the device. Then they are displayed but not set on startup..

**Comment by burnsfisher** [comment]
Oh, you are right.  I restarted 1.06g and the SNR was low.  I just clicked to the same value on gain master and it all fixed itself up.

**Comment by ac2cz** [comment]
This should be fixed and working in 1.07.

**Comment by ac2cz** [comment]
Let me know if this is working in 1.07b

**Comment by burnsfisher** [comment]
"Automatic" seems to be somewhat reasonable.

However--I set the gain master to full blast--495.  The noise floor and signal went way up, not surprisingly.  Then I stopped FoxTelem and restarted it.  The gain still reads 495, but the noise floor looked about the same as "automatic".  Then I pulled down the menu and let it stay on 495.  When I released the menu, the noise floor and signal hopped back up.  So it appears that on startup, FoxTelem is not setting the RTL-SDR value even though it remembered it.  The same happens if I stop the decoder before stopping the program and restarting it.  

If I just stop the decoder and restart it without stopping the program, the gain appears to stay correctly.

**Comment by burnsfisher** [comment]
Ok, this is fixed, more or less.  I noticed an odd behavior, and I'll send this back to you just so you see it.  Close, or tell me to re-open another case if you think so.

I notice that "Auto" seems to have more gain than the highest number possible to select on gain master (not in manual).   Everything (noise floor and signal) is maybe 10dB higher in Automatic than it is on 495.  495 actually decodes ok with my setup, but if I get to around 400, the loop locks and unlocks repeatedly.  (Noise floor at this level is about -60, signal is maybe -40).

**Comment by ac2cz** [comment]
Ok good.  Mostly working.  I will look at this, but moving from 1.07 to 1.08.
