### ISSUE TITLE
Fox1D Diagnostic For Camera Checksum is Wrong

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#424]
If you look at the raw data for time 0,6110, you see 17309196, which is hex 0x01081e0c  The LSB of this (0c) is correctly interpreted as the Gyro1V diagnostic.  However, the most significant byte (01) is being printed as 16 rather than 1.  In fact, I don't know why this initialized to 1, but it is, so if you subtracted 1 before displaying it, it would be much more clear.

I'm guessing this is the case for 1Cliff as well.

**Comment by ac2cz** [comment]
This was a bug.  Well spotted.  

I think I have the same issue with Audio Buffer Underflows which is alongside GYRO2V.  In each case I was 4 bits off.  Can you confirm that Audio Buffer Underflows should also just be the MSB.

Fixed in 1.06h
