### ISSUE TITLE
Any chance we could get installation instructions?

### ISSUE THREAD

**Issue by kf4mot** [ac2cz/FoxTelem#432]
In the readme for people that aren't linux wizards? I can get past the first step of cloning the repository. After that I'm pretty well lost though without some sort of guide to hold my hand.

**Comment by ac2cz** [comment]
Hi,

Are you trying to run the program or build it from the source?

Chris

**Comment by kf4mot** [comment]
Build from github. I suppose I'd be ok with either though.

**Comment by ac2cz** [comment]
There are installation instructions in the manual, which is a PDF. You
don't need to clone the git repo.

Right now there are no written instructions on how to build it. Email me if
you want to do that. Only needed if you are going to develop new features.
