### ISSUE TITLE
Display UTC Time on Health Page Only Affects New Data

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#433]
If I change "Display UTC Time" from checked to unchecked or vice versa, the actual Captured time does not change until a new data frame is downloaded.  Thus you can't depend on the check box to interpret the time that you see on the right since you might have checked or unchecked it since new data came in.

**Comment by ac2cz** [comment]
Duplicate.  Already reported by Alan in #427.
