### ISSUE TITLE
Make "Start/Stop" button clickable even if ""Start decoder when above horizon" is active

### ISSUE THREAD

**Issue by dm-o** [ac2cz/FoxTelem#435]
If "Start decoder when above horizon" is set, the "start" button is greyed out and not clickable.
If I want to test or manually start it I first have to go to settings and disable "above horizon".

This button should be manually usabele even if the autostart feature is set.

And I think it would be nice to bring the checkbox "above horizon" on the frontpage. A smal "auto start" checkbox next to or under the start/stop-button.

73
DO6DAD

**Comment by ac2cz** [comment]
Good suggestions.  These have been logged as Enhancements.

**Comment by ac2cz** [comment]
This is now part of the public release and I am going to close if there are no issues with it.
