### ISSUE TITLE
Suggestion: Wording for High and Low speed displays

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#440]
People still don't believe that there are two decoders running.  How about something like the following:

In the input section, you gave two radio buttons labelled something like 'Decode Type':  FSK and PSK.

Then down over the display, you have three radio buttons labelled something like
 Display: High Speed ()  Low Speed ()  Auto () and allow them to be clicked while the decoder is running.

**Comment by ac2cz** [comment]
Implemented in 1.07r

**Comment by burnsfisher** [comment]
Looks good!
