### ISSUE TITLE
Default "Find Signal when peak over..." is too high

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#451]
I know you originally suggested 12 when you changed the find signal algorithm, and Alan had some trouble with local QRM and said he was using 14.  It appears you have set the default to 14.  I suggest that this is too high.  

At 14, I was not getting locks on what looked like decent satellite signals.  When I switched it to 12, it locked in and I got perfectly good decodes.  Obviously the ability to change should be there for cases like Alan's, but I don't think that is best in general given my experience.  This was true of both DUV and PSK. 

Feel free to just close this if you disagree.  It won't hurt my feelings :-)

**Comment by ac2cz** [comment]
This is dependent on the local noise level. If the level is too low then it does not lock on regardless of the signal size.
