### ISSUE TITLE
RaspPi Error on Restart

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#465]
I powered down (i.e. pulled the plug!) on FIAB and after a bit plugged it in again.  On startup, FoxTelem 1.06q gave the message in the picture.  I stopped FoxTelem and restarted it again with the identical results.  Then I stopped FoxTelem,  renamed the telemetry/properties directory and started a clean new one.  Now it is ok.

Anything in the original directory is available if it
![screenshot from 2018-03-18 15 55 43](https://user-images.githubusercontent.com/2413372/37570641-770c8862-2ac8-11e8-9ad0-d2176c2693c7.png)
 will help.

**Comment by burnsfisher** [comment]
Note that I created a new label.  Feel free to remove if it does not fit your scheme.

**Comment by ac2cz** [comment]
I'm closing this as a duplicate of #141.  This is quite an old issue.  If the machine is in the middle of writing a file when the power fails then that file is corrupt and we crash at start.  No one has ever reported it before, but I have seen it on my home machine once after a power failure.  That said, there have been quite a few power failures and I have not seen this frequently.  If this is more common on Linux then I could increase the priority.
