### ISSUE TITLE
FCD Error Message on RasPi.

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#466]
See the error message in the screen shot.
The message is clear, but I don't know why it would be wanting to write to the FCD frequency.  I did not change it.  Nor why it could not--there is nothing else running.

Note that I had been running without "Autostart" checked apparently since yesterday when I restarted everything.  Then I checked autostart, but AO-85 was already above the horizon so it did not stop.  Then I pulled down the spacecraft menu and this happened.  I dismissed it, and things continued to work ok.

P.S.  The thing over on the right is something on the Mac.  This is a Mac screenshot of a VNC screen.

----------------
And Chris responded: 

Raise a defect.  I will add a check if the frequency has changed perhaps.  It looks like it was triggered as the frequency field was exited. It sets the frequency when the field loses focus.  That was based on a bug report from a user who could not work out why the frequency was not being set until I said you had to press enter....
<img width="864" alt="screen shot 2018-03-19 at 8 00 46 am" src="https://user-images.githubusercontent.com/2413372/37621206-a3ff5c56-2b94-11e8-84c9-050e7b591947.png">

**Comment by ac2cz** [comment]
Lowered priority as this is an error from the hardware device and its unclear how to handle it differently.

**Comment by burnsfisher** [comment]
Still happens sometimes on 1.07u.  Given that I don't know whether it actually HAS changed what I asked it to change, I restart the decoder and all is well.

**Comment by ac2cz** [comment]
Yes, I did not address this.  I moved it to release 1.08.

**Comment by ac2cz** [comment]
USB changes have all been moved to 1.09, but I may be able to mitigate this in 1.08 by checking if a value has changed.  That means we have to read the value from the FCD, but we only try to write if the value is actually different.  The read could still fail as this is interfacing with hardware, but it would half the number of operations and reduce the likely chance of failure.

**Comment by ac2cz** [comment]
I believe this is fixed with the changes in 1.10d, which retries this type of USB failure.

**Comment by burnsfisher** [comment]
Nope.  d3 did not do it.  New screen shot enclosed (and was also mailed to you).
![Screenshot from 2021-02-18 10-31-40](https://user-images.githubusercontent.com/2413372/108403796-1d700300-71ed-11eb-8166-59407a4e5bad.png)

**Comment by ac2cz** [comment]
Let me know if this is still an issue.  I have fixed another case for the RTL which is tracked in the parallel issue #687.  But that does not help this.  Looking at the code, this case seems to be covered and I am not sure why it does not retry.  One question I have is if the USB Errors total is updated after the dialog box is closed.  Meaning, did the retry operation work but the device was still unresponsive?  I can put the update of the retries before I open the error dialog to make that clear.  Right now it happens afterwards.

**Comment by burnsfisher** [comment]
This does not happen very often so I can't say if it still happens.  Only that it happened after you thought you had fixed it :-)  I'd suggest that you should update the count before the dialog box--most people are more likely to take a screen shot with the dialog box up even if we don't remember to check afterwards.

**Comment by ac2cz** [comment]
Ah, actually I have found another path where errors are not retried.  So I have fixed that.  They are now retried and we fail only if the USB bus fails 5 times in a row with a 200ms delay between retries.  I don't know what the optimal is, but we will test that.  So let's consider this fixed again in 1.12k

**Comment by burnsfisher** [comment]
I have not see this particular problem recently.   Occasionally, the RTL-SDR seems to disappear, but that is likely an OS problem.
