### ISSUE TITLE
Short PRN should not be an option on FoxTelem

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#477]
Since we are flying with long PRN, the checkbox (and particularly the default!) that allows short PRN should be removed from FoxTelem.

Most important for 1E flight as long as we remember for preflight testing :-)

**Comment by ac2cz** [comment]
It does default to TRUE in https://github.com/ac2cz/FoxTelem/blob/1.07/src/common/Config.java

But I agree this should no longer be optional because there is a chance that it is set wrong or that legacy settings are copied over.

**Comment by ac2cz** [comment]
Fixed in 1.07e
