### ISSUE TITLE
Crash in 1.07(uw)i

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#486]
I think this is happening with WOD data coming, and probably it is with duplicate WODs.  I'll try to get more details later.
![screenshot 2018-06-15 16 15 16](https://user-images.githubusercontent.com/2413372/41487703-a107fad6-70b7-11e8-91f5-d29fd51b2be6.png)

**Comment by ac2cz** [comment]
Ok, thanks for reporting.  Is this with real CAN data coming in?

**Comment by burnsfisher** [comment]
Yes, I think so.  I put the satellite in camera mode and I'm looking carefully, and I'm not sure UWs gadget is providing any camera messages.  So I may be sending something ugly too.  Not sure.  Will look more carefully tomorrow.

**Comment by burnsfisher** [comment]
Ah, I think the problem is likely that this is sending frame type 6 (CAMERA FRAME).  Should be essentially the same as type 5 except that it has different types of CAN messages.

**Comment by ac2cz** [comment]
I think I need a recording for this.  Or it may be that I have seen this bug and fixed it.  The line in the error message is no longer a valid line for a Null Pointer.  So I have clearly changed something.  The CAMERA frame is initialized the same as the SCIENCE frame already.

**Comment by ac2cz** [comment]
Wait on a recording and I will make you a new build.  Later tonight or tomorrow.

**Comment by ac2cz** [comment]
Thanks for the recording, I have reproduced here.  CAMERA frames are coming through as type 7, which I don't have defined here.  I thought SCIENCE are type 5 and CAMERA was 6.  Can you paste your frame enum here so that I can align to it?

**Comment by burnsfisher** [comment]
Not using an ENUM.  This is what I have.  Sounds like I may have a screwup
somewhere for camera even though this number matches your expectations.
(TYPES_OF_FRAME is used to size an array)

/* Define symbols for telemetry frame types */

#define ALL_WOD_FRAME            0
#define HEALTH_FRAME            1
#define MINMAX_FRAME            2
#define HEALTH_BEACON            3
#define WOD_BEACON                4
#define SCIENCE_FRAME            5
#define CAMERA_FRAME            6
#define TYPES_OF_FRAME            7

**Comment by burnsfisher** [comment]
My bug.  Got it...sorry about that!

**Comment by burnsfisher** [comment]
Fixed in flight software
