### ISSUE TITLE
Command counts and diagnostics are wrong in HuskySat

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#490]
V1.07m

HW Command Count and SW Command count in the ICR panel are both wrong and they behave oddly when switched from raw to interpreted values.  At least part of this may be because of the diagnostics, which is where I think those numbers come from.  They are mostly wrong.  I expect this is due to a few new values, although that does not fully explain it.  Let me know when you are ready, and we can get together about what is being sent.

**Comment by ac2cz** [comment]
These were right for Fox-1E in Flight Test.  Let me know if this has changed and I need a new layout or if the layout is the same and I have introduced a bug.

**Comment by burnsfisher** [comment]
It may have changed a bit since it seemed more important with the encrypted
commands to get an idea pretty quickly about whether they were accepted.
I'll check since I don't exactly remember.

**Comment by burnsfisher** [comment]
They are in the "realtime specific" area of type1 payloads, and they were in 1E also.  What happened is that we talked about adding in the full antenna status, and that's what I did.  To make the bits align nicely, I put the antenna status before the command ring buffer and counts.  It is in the SVN.

**Comment by burnsfisher** [comment]
There are other changes in the bit pattern there too.  For example, exp failure no longer exists, nor I2C for battery and PSU.  I2C for antenna is added.

**Comment by ac2cz** [comment]
For the HW and SW Command Counts, I may be confused.  For Fox-1E I just consider the number the actual count.  There is no conversion.  For Husky I have a special conversion and it says that the first 8 bits are the HW and the next 8 bits are the SW count.  But I see it is only 6 bits :)

So I presume this should work the same way as 1E, which is easy.  I just need to change conversion in the layout to 1, which is an Integer value.

**Comment by ac2cz** [comment]
For the ICR Diagnostic I may need a worked example.  My logic is this, and the code looks OK, but maybe there is a mistake:

32 bits holding 4 commands
In each byte the bottom 5 bits are the command and the top 3 bits are the name space
In a loop I do something like this:

loop 4 times:
    command = rawValue & 0x1f // command is least sig 5 bits
    rawValue = rawValue >> 5
    nameSpace = rawValue & 0x7  // nameSpace is 3 bits once we shift by 5
    rawValue = rawValue >> 3

**Comment by burnsfisher** [comment]
Sorry to make this so complicated.

The count appears in two places.  12 bits for each are in diagnostic 6.   The bottom 6 bits of those are in realtime telemetry hwCmdCnt and swCmdCnt (offset 600 and 606).  The idea is that we sometimes might want to know the total up to a larger number in case we are getting false commands, but the ground station would like to know nearly immediately if the command they sent got in (you can see 6 bits increment, but it is small enough that it would be real easy to wrap).

For the ring buffer, I need to look more.  I may have screwed it up.

**Comment by burnsfisher** [comment]
No, complex, but it is there.   The software ring buffer is in realtime data (and WOD) in a 4-byte array called swCmds.  Each byte is encoded like this

array[index]=(((shortinfo & 7)<< 5) | (longinfo & 0x1f))

So I think you have it right except I'm not sure why you shift raw by 3 at the end.  

Also, to distinguish where the end of the ring buffer is, immediately following the last (most recent) and entry with 0 for both namespace and command is inserted (so there are really one the last three commands in this 4-byte buffer).

**Comment by ac2cz** [comment]
No worries on the complexity.  
I have changed the conversion type for the HW and SW Command Counts that are in RT and WOD so that they just display the integer value.

I think the values were wrong because the layout changed.  The code looks right.  I have now updated the latest layouts.  

The summary for ICR Diagnostic does display the Name Spaces.  Is that OK?  Easy to change if we want the commands.  The Name Space and Command will take up too much room unless you have a clever set of short names.

**Comment by burnsfisher** [comment]
The name spaces are not as interesting as the commands, really.  The only
reason the name space is there at all is so that multiple groups could
create commands.  That has not happened, and certainly the commands are
unique without the name space.  It's useful to have command name unless
someone complains.  I'm pretty sure the FunCube displays the commands.  I
hardly think it is very revealing.

**Comment by ac2cz** [comment]
Ok, I will display the names of the commands.  This is fixed in the next version, likely called 1.07u (uw).

**Comment by ac2cz** [comment]
In 1.08
