### ISSUE TITLE
RTL-SDR Rules For Linux

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#491]
I got the RTL-SDR to work on Raspberry Pi by placing the enclosed udev rules file in /etc/udev/rules.d.  Otherwise you must use sudo to run FoxTelem.  (The file should be called rtlsdr.rules.  github will not allow a file with 'rules' on the end, so I added .txt.

Anyway, you might want to include this with the Linux distro when you end up supporting RTL-SDR.

[rtlsdr.rules.txt](https://github.com/ac2cz/FoxTelem/files/2325421/rtlsdr.rules.txt)

**Comment by ac2cz** [comment]
Ok, I can include these, but note you also need the rules for the FCD Pro Plus.  I have those instructions on my page for FoxTelem on the PI and you must have copied them down if it is working for you.  So I should perhaps bundle the fcd rules too.

**Comment by ac2cz** [comment]
Ok, these will be in the 1.07r release.
