### ISSUE TITLE
CAN WOD Displayed (and I assume decoded) wrong

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#493]
I'm reasonably sure that the latest HuskySat flight software that you have (C6.2f) is doing the right thing with whole orbit data, although if you give the umbilical command "enable canprint 4", which is supposed to show you the WOD CAN packets as they are sent, it looks wrong.  "g" has that fixed.  However, FoxTelem 1.07n looks like it is sometimes offset when interpreting the CAN messages (but gets the time correct) and other times seems to be interpreting an entire payload wrong with a totally bogus saved uptime and reset.

For example, here is what is being sent:

CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 2c 02 09 ]
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 2a 02 09 ]
CAN WOD Downlink for index 10, time 111/669:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 2a 02 09 ]
CAN WOD Downlink for index 11, time 111/733:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 54 09 2d 02 09 ]
CAN WOD Downlink for index 12, time 111/797:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=03 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 54 09 2c 02 09 ]
CAN WOD Downlink for index 1, time 111/93:
CAN Payload State Bits: 6, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 23 02 09 ]
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 24 02 09 ]
CAN WOD Downlink for index 2, time 111/157:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 27 02 09 ]
CAN WOD Downlink for index 3, time 111/221:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 25 02 09 ]
CAN WOD Downlink for index 4, time 111/285:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 26 02 09 ]
CAN WOD Downlink for index 5, time 111/349:
CAN Payload State Bits: 6, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 28 02 09 ]
CAN WOD Downlink for index 6, time 111/413:
CAN Payload State Bits: e, max is 71
CAN size=7,id=12390246, data=02 05 20 05 20 05 20 ]
CAN size=8,id=12390263, data=08 d5 09 3b 09 26 02 09 ]

and a screenshot of some of what FoxTelem shows is attached.
![screenshot 2018-09-03 15 28 55](https://user-images.githubusercontent.com/2413372/44999846-4012f080-af8e-11e8-8c94-affe0bb40561.png)

**Comment by ac2cz** [comment]
I agree this looks like a bug I have introduced.  I can reproduce it with the test WOD file you made for me a while ago.  I think the layout of WOD CAN Payloads is still the same, but the data looks a mess, just as yours does above.

**Comment by burnsfisher** [comment]
This seems ok now.
