### ISSUE TITLE
Hard (impossible?) to copy/paste data from payload lists

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#494]
If you make the text list of payloads show by pulling up the divider, it is not possible to select multiple lines (at least not using the standard Windows "shift click" or "ctrl click"), and thus you can't copy them to the clipboard for pasting elsewhere.  Of course with graphs you can click on the 'disk' icon, but there is no such thing for the full payload list.

If there is another way to do this, please let me know.  Otherwise, you get screenshots in other issue reports :-)

**Comment by ac2cz** [comment]
I agree shift click and control click do not work and that should be fixed.
As a work around dragging the mouse with left click selects multiple rows.

Chris

**Comment by burnsfisher** [comment]
Thanks.  I would not have thought of that.

**Comment by ac2cz** [comment]
Implemented in 1.07r

**Comment by burnsfisher** [comment]
Very nice!  Thanks.
