### ISSUE TITLE
New Diagnostic for HuskySat

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#499]
Diagnostic type #18 is of the type with 2 12-bit quantities.  The first is the voltage at which it will go into autosave; the second the voltage at which it will come out.   The values are ADC counts which can be run through the MCU's ADC to voltage table and then should be multiplied 99/25 (i.e. about 4) to get a voltage.

I guess there is not a "Medium" priority available.  But as long as I can read it raw, it will be ok for the moment.

**Comment by ac2cz** [comment]
I need the definition for Diagnostic Type 17 too.  The last Diagnostic I have is number 16 which is the ISIS Status.  I also have Bus Voltage Over 2 in a comment as number 15, but because it is commented out, 15 is not defined.  Perhaps you should review against your code?  Mode full list below:

	// Flattened C ENUM for IHUDiagnostic Error Type
	public static final int SPININFO_1 = 0;
	public static final int SPININFO_2 = 1;
	public static final int SPININFO_3 = 2;
	public static final int SPININFO_4 = 3;
	public static final int LAST3_DL_STATES = 4;
	public static final int COMMAND_RING = 5;
	public static final int COMMAND_COUNT = 6;
	public static final int I2C1_ERRORS = 7;
	public static final int I2C2_ERRORS = 8;
	public static final int GYRO1Z = 11;
	public static final int GYRO1V = 12;
	public static final int GYRO2V = 13;
	public static final int UNKNOWN = 15;
	public static final int IHU_SW_VERSION = 14;
	public static final int ISISStatus = 16;
	//public static final int BUS_VOLTAGE_OVER_2 = 15;

**Comment by burnsfisher** [comment]
Type 17 is static.  It should always be the same for a given satellite.  It is the calibration voltage value that the manufacturer burns into each processor for the temp.  The 24 bits of data should be the temperature calibration value.  I'll help you figure out how to interpret it in a bit.

**Comment by ac2cz** [comment]
Ok, no issue on 17.  I will just display the 24 bit number for now and you can tell me what it means later.  I have this stored in a look up table anyway.

For type 18, I have a raw value of: 158334738
First 8 bits give 18 as expected.
The next 12 bits give 4095
The last 12 bits give 150.

That does not sound right...  Is it correct?

**Comment by burnsfisher** [comment]
Ok, I hate to give this back to you, but..first, the autosafe is fine, I think.  I had it messed up in the flight software.  Besides new flight software enter the command "set autosafe usb" to ensure that the MRAM is correctly initialized.  (preflight init will also do it, but that would wipe out a lot of other stuff).

About the temp calibration:  This is the ADC value for 30 degree C and for 110C.  It does not change except from one chip to the next.  But given that I can change the ADC value by changing parameters to it, it's only a bit interesting, maybe for calibration sometime should we care.  So you could translate it as a temperature, or you could translate it as a percent off, or you could just print it as a raw number.  (If you have a chance sometime you might use it to calibrate your IHU temp values, but it's probably not worth it).

**Comment by ac2cz** [comment]
There is a lookup table that I use for the IHU temp.  It could have been automated from the values here I suppose, but the lookup table approach is already done.  It uses the 2 values and a value at either end of the scale as I remember.   So these values need to be added to the lookup table once we have the flight model.

Is this left open so we remember to do that?  Of is it because the IHU temperature values are not being broken out and displayed?

**Comment by ac2cz** [comment]
Ok good.  I wanted to understand them and make sure we had not missed anything.  I will close.  We will add the FM IHU values to the lookup table when in Flight Test.
