### ISSUE TITLE
HuskySat Telemetry does not show the modes correctly

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#502]
FoxTelem does not display the HuskySat modes correctly.   See #471 (toward the end) for a screen shot.  HuskySat has the modes explicitly in the header, but the FoxTelem heuristic that looks at bits within the payloads does not seem to work correctly in some cases either, especially relating to safe mode.  For Husky, the display should be switched over entirely to using the new header bits.

**Comment by ac2cz** [comment]
In 1.08

**Comment by burnsfisher** [comment]
Looks perfect except...camera mode, which is bit offset 59 (science is 58, health is 57) shows as "Unknown".

**Comment by ac2cz** [comment]
Ok, very good.  I "forgot" about CAMERA mode.  How do I get it into that mode without an actual camera?  Is it just an IHU command?

**Comment by ac2cz** [comment]
Camera mode added in 1.08a

**Comment by ac2cz** [comment]
Can this be closed?

**Comment by burnsfisher** [comment]
Sorry, yes.  I saw Camera mode working in 1.08f.  Thanks!

**Comment by burnsfisher** [comment]
Sorry, I have to reopen this.  Not quite right.  Download the current HuskySat download from the server.  It is currently in safe mode, and that displays ok.  However, if you select from the text data at the bottom and go back to before the satellite was in safe mode, FoxTelem briefly displays the mode that it was in when the selected data was received, but then switches back to displaying 'safe mode'.  This is true on both 1.08z5 and 1.09g

**Comment by burnsfisher** [comment]
I've marked this as critical.  It is still a problem in 1.09i, and it makes it very difficult to track what is going on in the past.  I suspect that the issue is that the "safe mode" bit in the telemetry is not set--probably because that bit is in a payload that is not actually sent in safe mode <dope slap to WB1FJ>.

**Comment by burnsfisher** [comment]
Ok.  What I really want to do is to be able to step through the records to look for when the mode changed, and generally that is near the most recent received, so I generally use live.  I can switch to Next and enter some previous time...only a bit more complex.  Removing "critical".  But I'm going to copy my email to you in the next comment.

**Comment by burnsfisher** [comment]
For any of the tabs (Health, WOD, CAN, etc) there are two display modes (as opposed to satellite modes) to my way of thinking.  One is to look at the most recent data in the panels.  In that case you don't care about the list of records below.  If you want to look at a graph of a particular bit of data you can easily do that by clicking on it.  Let's call this "realtime display mode"

The other display mode is to be able to look at the list and click on a particular line and either look at all the columns for that row and see the raw values, or more likely see them translated on the panel above.  For this mode, you also want to be able to scroll through the data in order to see in detail what has changed from one packet to the next. Let's call this "historical display mode"

I think that the problem regarding the original bug is that we are conflating those two display modes.  It's not obvious which display mode we are in--looking at records from the list, or looking at the most recent.  I'd suggest that THIS is what we really want to be clear on.  Currently if you open the list, you are still in "realtime display mode".  If you click on a list item you are in "historical display mode" except with the "Live" button when there is kind of this hybrid behavior (I think).  And worse, it is not clear (to me) how to get back to "realtime display mode".

I'd suggest a couple things:

1) If one is in historical display mode, one is completely in historical mode.  The panel displays only the date from the list entry  that is selected.
2) If the list is showing, you are in historical display mode.  If this list is hidden you are in realtime display mode.  Maybe you want to make the "hide" and "show" list buttons a bit more obvious, but that is the general idea.
3) To reduce confusion, if you scroll through the list with the arrow keys to select different records, the list itself should scroll so that the highlighted row is always visible.  A highlighted row is a clear clue of which row/what time is being displayed on the panel.  Of course if you scroll through the list with the scroll bar, you kind of have to hide the selected record.  But then an up arrow or down arrow should jump to the highlighted row.

Anyway, given that there is a way to find the mode you are in, I have removed the "critical" marking on the issue.  But I think that even though maybe only a few of us use this feature, we are often looking at a complex sequence of events, and making it easier is important.  Thus I made it "high" instead.

**Comment by ac2cz** [comment]
I've been pondering this for a couple of hours, trying to think of the best way to display the mode and allow analysis.

First of all, for LTM-1 let's put the MODE as the first byte in every payload and remove 1 byte from the header (or two bytes if you want).  Then all of these issues get easier.  Mode will be displayed on the panels at the top of the page, it will be included as a field in the graphs, it won't appear and vanish as you look at records.  

What if I stop showing the current mode of the spacecraft on the Health Tab and instead show the current mode for the spacecraft on the Input tab.  Perhaps next to the Position data top right.  That can always be the latest.  Then the Health tab will just show the mode for the health record that is being displayed. Either the latest or the one selected in the table.

The proposal you make about which display paradigm we are in, Live or Historical, is good.  This is not just an issue for the mode.  If you are browsing a record and a more recent health record is received, then I believe that is shown if LIVE is displayed bottom right and it is not shown otherwise.  So it is the same issue.  I can make the show/hide buttons on the horizontal divider larger.  Is it enough to collapse it, or do we need red text at the top saying "Historical Data being displayed" given this may confuse some people?

**Comment by burnsfisher** [comment]
Those all sound like good ideas, Chris.  Is it, in fact, possible to make the historical data scroll as you move the selected one along?  That could also be an indication that you are in historical mode: That a historical datum is highlighted.  But an obvious text is probably better.  Maybe by the time?

About the mode being the first byte of every payload--I'm good with it being every payload.  The problem is that right now the first n bytes are defined as the ones that do min/max.  In addition, each "section" really works far better if it is aligned on 32-bit boundaries.  I could work around that, but here are a couple alternate thoughts:

Suppose that *to me* the mode was the last byte of the header.  Your software doesn't care so much as mine about having different sections aligned to 32-bits, so could you just "pretend" that the header was one byte shorter? (That kind of messes up the spreadsheet we share though.  Hmm.  Alternatively, what if the mode byte was consistently at the same location in each payload, but not the first byte?

If those don't seem as good, let me see what I can do for the first byte.  Maybe I can find 3 more bytes of useful stuff to put there with it.

**Comment by ac2cz** [comment]
Let's close this as it has become about GOLF/LTM-1.  The Huksy issue is resolved.
