### ISSUE TITLE
Audio Output causes error on Raspberry Pi

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#513]
I know we have talked about this, but I don't that it was reported as an issue.  The Raspberry Pi DOES have an audio output.  However, occasionally when you select "Monitor Audio" you get an error (Screen shot included here).  The box is too long to actually get the dismiss button at the bottom, but you can hit the "x" to get rid of it and the decoder continues to work.

This is not a huge problem except for being confusing to FIAB users.  It may be more troublesome when the decoder starts up with monitoring turned on.  I'll try to be sure it is off by default on images I send.  BTW, it does not happen all the time, so we don't always notice it.

**Comment by burnsfisher** [comment]
<img width="819" alt="screen shot 2018-11-08 at 8 56 59 am" src="https://user-images.githubusercontent.com/2413372/48203261-0915de00-e335-11e8-9641-2f440b4b8431.png">

**Comment by burnsfisher** [comment]
Oh, this screen shot comes from 1.06q but it was also reported on 1.07m.

**Comment by ac2cz** [comment]
The long error box issue is fixed in a later version. I will have to look
at what caused it.

**Comment by ac2cz** [comment]
This was an unchecked creation of the output device.  I added a check for null.

This situation is fixed in 1.07u, but there may be other places where the output device can cause problems, such as in #521

**Comment by burnsfisher** [comment]
The long error box is certainly fixed.  Thanks...

I can force something similar to happen by explicitly selecting the ALSA sound device on a Pi and turning it on and off a couple times.  However, it is NOT a null pointer exception, and if I dismiss the error, the decoder keeps going.  All for the good, I think.  I'll close this one since the error actually reported is fixed.
