### ISSUE TITLE
The CAN Packets that are shown in FoxTelem are not all forward to COSMOS

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#517]
Testing at UW has shown that all of the CAN Packets that are shown in FoxTelem

See #492, #496 to make sure that his is not a past defect that has been fixed.

**Comment by ac2cz** [comment]
Another bug fix in FoxTelem and a bug fix in the IHU appear to have mostly resolved this.  We are now losing 1 packet in 300 seconds with the Costas loop coherent decoder.

Garret has also identified a fix to windows audio drivers that helps.  Details to follow.

**Comment by garrettdreyfus** [comment]
Hello,

After a night of testing, we lost around 20-30 packets out of ~35,000 so an
incredible improvement! We also had 0 audio missed. This was after
installing the ASIO4ALL driver from this site http://www.asio4all.org/ and
turning off all audio sources except the FunCube dongle.

Garrett
