### ISSUE TITLE
Uncaught Exception on FIAB for 1.07t

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#520]
When trying 1.07t on a Raspberry Pi with a fresh data directory, it installed the spacecraft as expected, and showed the input screen.  When I tried to start it (FCDPP) I got this message.  

It appears that the 'started' bit got set in properties, because now when I launch the program, I get the same message (as shown in the picture) immediately.

Further, after I killed this program and started the old 1.06m (I think) version with its old data, etc, it appeared to start ok, but the HID stuff was not displayed, only the FFT.  After rebooting the Pi it looked normal again.  I'll try to track down a bit more with 1.07t after I delete the properties so I can start it up again.
![screenshot from 2018-11-19 10 24 58](https://user-images.githubusercontent.com/2413372/48717088-b23abf00-ebe6-11e8-8f11-664a4468db01.png)

**Comment by burnsfisher** [comment]
Slight update:  Same behavior both with DCO and without.  And next time I tried it, I did get the LNA Gain, Mixer Gain, etc when I went back to the old version.

I also tried running it with sudo in case it could not access those devices.  No change.

**Comment by ac2cz** [comment]
This one feels familiar.  Didn't I forget to bundle the ARM USB libraries last time as well?  Anyway, good catch.  I need to package the run time libraries into the jar file.

**Comment by burnsfisher** [comment]
I don’t remember if that was a previous issue, but glad it is clear what
the problem is. Tnx.

**Comment by ac2cz** [comment]
Fixed in 1.07u

**Comment by burnsfisher** [comment]
Ok for 1.07u on a Pi.
