### ISSUE TITLE
Download from Server on Pi does not display

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#522]
Reported by an FIAB owner, confirmed locally:  With 1.07u (and at least as early as m) if you "Download From Server" it does delete your old data files, it appears to download (takes forever) and uncompress, and it appears to leave a bunch of file in the DATABASE directory.  However, nothing displays on the health screens, and "Payloads" shows as 0 on all satellites.  We have not figured you yet what will happen (if anything) when one of the downloaded satellites actually comes over and gives new data.

**Comment by burnsfisher** [comment]
More info:  When AO-92 came over and the FIAB collected 15 frames, that data went in the top level of the data directory.  The download went into the DATABASE directory, and while files were created at the top level, they were 0 length.  So that is the difference between server data and decoded data.

**Comment by ac2cz** [comment]
This sounds like an environmental issue with the directories mismatched.  I will investigate and see if there is a bug.

Note that server data and local data should go in two different directories, as mentioned in the manual.

**Comment by burnsfisher** [comment]
I'm reasonably sure that I cleaned out all the directories and started from scratch to test this out.

**Comment by ac2cz** [comment]
I can't reproduce this. It might only happen on linux or on the PI.  I need a log file to help debug.

I tried the following to reproduce:
If 1.07x is run with a directory as the first paramater this runs fine.  The data is downloaded and loads into the tabs as expected.
If you run with the config in ~/.FoxTelem directory then it also works as expected.
If you try to extract into the current directory then an error message prevents you.

**Comment by burnsfisher** [comment]
It's easy to reproduce on a Pi.  I'm trying to get a log now.

**Comment by burnsfisher** [comment]
[FoxTelemDecoder20190308.log](https://github.com/ac2cz/FoxTelem/files/2944168/FoxTelemDecoder20190308.log)

I'm not sure if this log is helpful.  I deleted spacecraft AO-85 to reduce the time it takes to uncompress (which is forever even so).  Still no data on the screen when it completes.

I can give you access to this FIAB if you wish.

**Comment by ac2cz** [comment]
I think I know what the issue is with this.  See in the screen shot below that I sometimes have Fox and sometimes FOX, such that we end up with the same file names, but as duplicates.  On Windows they probably overwrite and don't cause an issue.  But on Linux it matters.  Is MacOs case sensitive for file names?  It must not be.
![image](https://user-images.githubusercontent.com/14824793/54064243-8452a800-41e0-11e9-9a83-f52eabb50779.png)

**Comment by burnsfisher** [comment]
Aha!  Yes.  Mac is not case sensitive.

**Comment by ac2cz** [comment]
This was a server issue and is now fixed.  Try re-downloading the data

**Comment by burnsfisher** [comment]
Works fine now!
