### ISSUE TITLE
The spectrum freezes a few seconds after hitting the start button

### ISSUE THREAD

**Issue by murd0cun** [ac2cz/FoxTelem#523]
Hi,

I am using a signalink connected to my FT-847. If I hit the start button, the spectrum and all other graphs in the output section start moving but after a few seconds they freeze. If I hit the stop and start button again, they will start moving again for a few seconds then halt again.

At this point I am not sure if the telemetry decoding is also affected or the software still decodes the signals behind.

I have tried different Source settings but no luck.

Thank you and 73!
Zoli, YO3GCI

**Comment by ac2cz** [comment]
Can you post a screenshot?  Which platform are you on, is this windows?
Is the Signalink passing the audio unfiltered to FoxTelem?

**Comment by murd0cun** [comment]
Hi,

I am attaching a screenshot of the problem. The spectrum remains exactly how it is captured in the print screen attached.

Platform is Windows 10, on a gaming ASUS RoG laptop.
The signalink is passing audio unfiltered and unaltered in any way.
The FT-847 is not yet connected to the software via CAT.

Thank you!
Zoli

![image](https://user-images.githubusercontent.com/45143034/49337256-48280e00-f619-11e8-8346-796afd630a1b.png)

**Comment by murd0cun** [comment]
Hi,

Not sure if this is the normal functionality of the software but it turns out that immediately after it freezes, I can use the ">" button on the "Audio Options" right bar and unfreeze it. It looks like it is automatically hitting the pause button a few seconds after I press the "Start" button and all I need to do is hit the ">" button to start it back again. Strange behavior.... 

Thanks,
Zoli

**Comment by ac2cz** [comment]
Yes, you are in a debug mode that is very useful in testing from a recording but not much use beyond that.  In the display you see the audio sliced into the bits that FoxTelem will sample.

If you go to File>Settings and remove the check mark from "Debug Values" then you will be out of this mode.
