### ISSUE TITLE
FoxTelem 1.07m Stops In The Middle Of A Pass

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#525]
Ed Krome, who has a downloaded FIAB, reports that his Pi stops in the middle of a pass if he has either box in "Measurements" checked in the preferences panel.  In particular with "Start when satellites is overhead", it does start and run for a bit and then stop before LOS.  

It just occurred to me to have him double check that his dongle is tight in the USB plug, but what log items would be helpful to debug this?  I suspect it is not a general software error since I have not seen it on any other FIAB.

**Comment by ac2cz** [comment]
When it "stops" what happens?  Crash?  Freeze? Or just no decode?

A screenshot would be good. 

Turn on logging and send me the log right after a pass. If there are lots of passes I will need to know the utc time of the pass to look at in the log.

**Comment by burnsfisher** [comment]
He told me it stops just like you pushed the stop button.  He can restart
it pushing the start button.  Will ask for log.

**Comment by ac2cz** [comment]
Do we every get a log for this?  Otherwise I am going to close as not reproducible.

**Comment by burnsfisher** [comment]
Never got a log.
