### ISSUE TITLE
Odd behavior if computer has gone into sleep

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#526]
This may relate indirectly to #509.  I believe I accidentally put my computer into sleep or suspend of some sort.  It came back out when I touched the KB and everything looked ok.  However, when Fox-1Cliff came over I was getting nothing.  Not even its cohorts that are usually signalling more frequently.  However, there was enough showing on the FFT to see that I was at least getting a signal of some sort.

I hypothesized that the FCD LO got messed up in starting and stopping.  In fact, stopping all copies of FoxTelem and restarting the Cliff version restored behavior just fine.

I'm sure this is a Windows/FCD issue.  However, I'm thinking that this is yet another case of what can go wrong when you have no control over the HID and when you do not even read and display it.

So when you get around to doing something in this area, here is another possible symptom to consider.

**Comment by ac2cz** [comment]
This seems to be a windows audio issue.  I have seen it too.  The solution is to not allow your computer to go to sleep, or to start/stop the decoder if it does go to sleep.  Unfortunately there is no way for me to know that windows has disconnected the audio from Java.  

I will make sure that is clear in the manual for the 1.07 release.

**Comment by ac2cz** [comment]
The 1.07 manual has been updated with a note about the audio disconnect during sleep

I agree this could also be the issue of managing the FCD across multiple programs.  Given #509 is tracking that, I am going to close this one.  I moved #509 to 1.08 as it is too big a change to now add to 1.07.
