### ISSUE TITLE
not a software but hardware issue

### ISSUE THREAD

**Issue by zanco** [ac2cz/FoxTelem#531]
Hi, I do have an issue with my new radio and the Fox 1 telemetry tool. With SDR all went OK but on either the USB or the DATA output of the FT-991a I am unable to decode. Signals are quite strong, even the eye appears but there is always a horizontal line through the eye.

![fox1-bad-eye](https://user-images.githubusercontent.com/4477734/50765627-c316c100-1276-11e9-9bae-0d7cb77f3827.JPG)

Could anyone give me a suggestion what is wrong ? If I feed the decoder with the audio from a repeater with CTCSS I hear the CTCSS sound humming when I monitor audio, so the lower frequencies appear to pass. I had a 600 Ohm transformer between data out and line in on PC but with or without transformer the results are the same.

Both the decoder and the audio card are set to 48000 so I am becoming a bit clueless.

APRS 1200 baud on the decoder output to aprs software does decode 

Thanks for the help.

Ben - PE2BZ from the Netherlands

**Comment by ac2cz** [comment]
Ben,

The bits do not look normal, so something is filtering them.

Play a test recording from another device (laptop, phone, iPod) and feed
the audio into the sound card. That should decode fine, confirming the
sound card and FoxTelem configuration.

You can test the output of the radio by listening to the audio with a sound
card spectrum analyzer. There is an example of this in the manual. Are the
low frequencies filtered?  Are there settings on the radio to remove
filtering?

Chris
