### ISSUE TITLE
FoxTelem periodically crashes when receiving packets from HuskySat

### ISSUE THREAD

**Issue by garrettdreyfus** [ac2cz/FoxTelem#532]
When run from console mode FoxTelem will freeze up, until Control-C is entered in the console. Once Control-C is entered FoxTelem continues to operate as normal. I have seen this issue three times. Two times it immediately resumed after hitting Control-C and once it required multiple Control-C presses for FoxTelem to resume.

Here is the console directly after one of the crashes. 

![image](https://user-images.githubusercontent.com/3867825/51358027-068adf80-1a6e-11e9-80c0-ae3d7ba0ce65.png)

**Comment by ac2cz** [comment]
This seems to be an issue with the Cmd prompt.  If you have git bash or MSYS installed then try running it from a bash terminal to see if you get the same issue.

This is discussed here: https://superuser.com/questions/1066972/windows-10-command-prompt-running-programs-freeze-until-ctrlc
and here: https://superuser.com/questions/312132/command-prompt-hangs-until-keypress which suggests it is an issue with the quick edit settings.

**Comment by ac2cz** [comment]
I'm closing this because its an environment issue and not an issue with FoxTelem,
