### ISSUE TITLE
FoxTelem doesn't save port number immediately

### ISSUE THREAD

**Issue by garrettdreyfus** [ac2cz/FoxTelem#533]
When changing port number Cosmos did not receive packets. I opened wireshark and it showed that FoxTelem was still sending to the old port. After opening the HuskySat settings and immediately closing it began sending to the correct port.

**Comment by ac2cz** [comment]
This is fixed in 1.08b

**Comment by ac2cz** [comment]
Assigned back to @garrettdreyfus.  Please close if this is not longer an issue
