### ISSUE TITLE
Crash on 1.07V/Raspberry Pi

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#536]
I had stopped the decoder, switched to NCO mode, restarted it.  Then stopped, switched off NCO mode, and then this happened when I restarted it.  I have not tried to reproduce.

BTW, NCO mode uses just a bit more CPU on the Pi compared to the old way (65% vs 60).  Not what I expected.  

(Oddly, the percentage does change over time.  I suspect when it is hot, the chip slows down.  Sometimes I can get 100% when I'm watching the Input screen on VNC).

**Comment by burnsfisher** [comment]
<img width="1095" alt="screen shot 2019-01-28 at 9 21 03 am" src="https://user-images.githubusercontent.com/2413372/51842629-545dde00-22df-11e9-9108-0608e5214103.png">
Forgot to leave you the screen shot.

**Comment by ac2cz** [comment]
This is likely the same root cause As #535

**Comment by burnsfisher** [comment]
Ok, I'll close this one and leave #535, although I notice that 535 has no assignee.
