### ISSUE TITLE
Odd scanning/locking behavior on 1.07v

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#539]
Generally the FIAB with 1.07v has been working wonderfully with NCO.  But I happened to be watching during an AO-95 pass.  FoxTelem had the keps right and started the decoder, but the demod bars stayed in the AO-91 frequency band despite a strong signal from 95.  I manually clicked in the AO-95 area and got one frame and 2 minutes later 2 more near TCA.  They were decoded and sent on to the server.  HOWEVER, the screen still said "Scanning AO-91".  A couple minutes later as the doppler was shifting faster/lower, there was again a strong signal, but it did not adjust the frequency at all, and did not decode it.  The screen still says "Scanning AO-91".

I remember you said that with NCO, the modulation bars are really just user feedback and don't mean much, but I did notice that I had not gotten any decodes at all from 95 (a number from others though).So I don't quite know how to understand this.  I have a couple of screen shots.  Unfortunately not during a successful or unsuccessful decode, but you can see what the screen looked like.

Question:  Do you use the keps to decide where to 'start' looking for a signal?

<img width="711" alt="screen shot 2019-01-30 at 9 50 50 am" src="https://user-images.githubusercontent.com/2413372/51990413-f7952b80-2476-11e9-810b-0aca31d72013.png">
<img width="719" alt="screen shot 2019-01-30 at 9 51 35 am" src="https://user-images.githubusercontent.com/2413372/51990416-f8c65880-2476-11e9-8dba-cebfcf56c4b1.png">

**Comment by ac2cz** [comment]
I think this is the same issue/bug that Alan reported with the NCO.  It should be fixed in 1.07x.  Try running with "Fox Telem Calculates Doppler" OFF and "Follow Doppler" ON while in NCO mode.  We should no longer see this behavior.

**Comment by burnsfisher** [comment]
I was running FoxTelem Calculates and it seems much better.  Thanks!
