### ISSUE TITLE
FoxTelem crashes with Serious EDT error

### ISSUE THREAD

**Issue by garrettdreyfus** [ac2cz/FoxTelem#540]
![image](https://user-images.githubusercontent.com/3867825/52016897-3e444f00-2492-11e9-9804-34d08b127abf.png)

**Comment by ac2cz** [comment]
Any more details you can share?  What was happening when this crashed?
Which version are you running, it does not show up in the screenshot.

**Comment by garrettdreyfus** [comment]
I’m not sure I have much additional information. We were running 1.08. This
time not from the console.

**Comment by ac2cz** [comment]
I'm going to close this as I don't have any information to debug it with.  The error message is not helpful and I can try to address that, but it is hard to pop a message up for the user if the GUI framework itself has the issue. The EDT is the Java Swing Event Dispatch Thread, so the GUI has stopped working.

Make sure you have logging turned on in the lab and send or attach the section of the log that covers issues like this if possible.
