### ISSUE TITLE
FoxTelem Crashes When It Decodes an Unknown Satellite

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#541]
I'm working on Golf-T and happened to send telemetry.  It crashed FoxTelem (array overflow I think) since it was satellite 7.  It's fine for FoxTelem to check for known satellites, but it should either just increment a count of unknown satellites, or ignore it rather than crashing.

**Comment by ac2cz** [comment]
Let me know if it is going to delay any testing and I can build a version that works.  When do you think you will first try to run dummy telemetry through?

**Comment by burnsfisher** [comment]
To be honest, there is no rush.  Right now the only thing I wanted to
change was the fields and names relating to the antenna.  The ISIS antenna
has a lot of stuff that we will not be sending.

**Comment by ac2cz** [comment]
Hard to know if I fixed this. Happy to test if you give me a rudimentary Golf-T build that will work on my hardware.  Or you can give it a quick test.  It will be in 1.08g

**Comment by burnsfisher** [comment]
Ok, I'll just check it to be sure it does not crash.  When we really get
the telemetry set up, I'll be sure you have a "7." version.
