### ISSUE TITLE
"Raw Bytes" for CAN: Columns not right

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#546]
First, Chris says he left out the length field so the columns are not correct.  Chris also mentioned the order not being correct, but he already has that logged separately.

**Comment by ac2cz** [comment]
I fixed the display issue in 1.08f.  The ordering still needs to be addressed

**Comment by ac2cz** [comment]
I think this is fixed in 1.08g.  I can't remember what the ordering issue was, but it seems fine with my test data.

**Comment by burnsfisher** [comment]
Ok, I don't recall either exactly.  I suspect this may be at least partly the old issue where it is difficult to get a display is double-key order (i.e. all reset n in uptime order followed by all reset n-1 in uptime order, etc).  I think you said that was not easily fixable using the display package you had.
