### ISSUE TITLE
Husky IHU (LTI) A/D Converter Calibration

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#554]
This is really pretty darned linear!  I'm guessing that most of the variation comes from not being able to adjust the power supply that finally.  I kind of blew on the knob to adjust it :-)  First one is S/N 32.  I will have S/N 31 later.  I don't know which will be flight and which will be spare.
[IHU Checkout SN32.xlsx](https://github.com/ac2cz/FoxTelem/files/2999785/IHU.Checkout.SN32.xlsx)

**Comment by burnsfisher** [comment]
Here is S/N 31.  They look very similar.  I suspect as above most of the difference is my inability to adjust the power supply closer than a few hundredths of a volt.
[IHU Checkout SN31.xlsx](https://github.com/ac2cz/FoxTelem/files/2999809/IHU.Checkout.SN31.xlsx)

**Comment by ac2cz** [comment]
Ok, very good.  I put the lookup tables into files with the S/N and the lookup table to be used is then specified in the spacecraft.dat file.  So we can change it at will depending on which is the FM and which ends up being the spare.

**Comment by burnsfisher** [comment]
Ok, sounds good.

**Comment by ac2cz** [comment]
Just to make sure I understand the spreadsheets that you attached, because there are lots of columns. I have a lookup table for VBATT vs ADC that was created for Fox-1A and which we use to get back to the voltage sensed.  So I have two columns.  The first is the ADC value and the second is the Voltage * 2.

You have a Voltage and an Exp 4 Reading ADC value, but also a Bus Voltage and some other ADC values.  Which do I use?

**Comment by burnsfisher** [comment]
Ah, sorry.  There are two sections.  One is for 0 to 3.3V.  You want to the first two columns.  A is the measured voltage.  B (Exp4 reading) is the a/d converter reading.  It's called exp4 because that thermistor that used to be on experiment 4 is the most easily accessible line that I can put my power supply one.

The second column is only 3.3 to 6.3V and is the Vsys (or Vbus) reading taking into account the voltage divider that we had to use.  This was 50/50 on the Foxes, but on Husky it closer to 1/4.  You want "bus voltage" column A and Vbat/4 Reading, column C.

The other columns are there mainly for checks and for curiosity.   For example, 1.V Delta is just determining at that point what ADC count corresponds to .1V.  Linear says "If this ADC were strictly linear, what would the reading be" and "Diff" is the difference between linear and actual.  As you can see it is pretty darned linear with a small offset.  The changes in dif could largely my my inability to adjust the test voltage exactly.

The only difference on the second section is that Voltage/4 is the calculated voltage being ready by the ADC after the voltage divider, and is used to calculate the linear and dif columns.

So really you only need to pay attention to the two columns I mentioned.  The rest are for our amusement.

**Comment by ac2cz** [comment]
This is implemented in 1.08g

**Comment by burnsfisher** [comment]
I'm just going to close this since I don't have the actual devices any more.
