### ISSUE TITLE
ICR Array overrun exception

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#555]
This is being broken out of #552 so that the ant status can be tested and closed independently.

Here is the screen shot of the issue:

![image](https://user-images.githubusercontent.com/14824793/56624931-e9cfec00-6608-11e9-9915-e3a4ccbb3cde.png)

And recommenting here:

The exception is for the ICR Diagnostic, not the regular diagnostic. We should probably have it in a separate issue. I have the following name spaces defined. Perhaps I am missing one or more?

	// Flattened C ENUM for ICRDiagnostic Command names in Ops Namespace
	public static final String[] SWOpsCommands = {
	"Unknown", //0
	"SafeMode", //1
	"TransponderMode", //2
	"ScienceMode", //3
	"DisableAutosafe", //4
	"EnableAutosafe", //5
	"ClearMinMax", //6
	"OpsNoop", //7
	"ForceOffExp1", //8
	"ForceDeployRx", //9
	"ForceDeployTx", //0xA
	"ResetIHU" //0xB
	};

	// Flattened C ENUM for ICRDiagnostic Command names in Tlm Namespace
	public static final String[] SWTlmCommands = {
	"Unknown",
	"Gain",
	"WODSaveSize",
	"Encoding",
	"Frequency"
	};

	// Flattened C ENUM for ICRDiagnostic Command names in Exp1 Namespace
	public static final String[] SWExp1Commands = {
	"Unknown",
	"CycleTiming",
	"SetBoard"
	};

**Comment by ac2cz** [comment]
This is the same issue that Eric reported last week.  It looks like the ICR value is outside the range of the enums that I have.  I can add some more code to print out the error more clearly if we can't spot the error from the reference data I posted above.

**Comment by burnsfisher** [comment]
Ok, I understand now.  There are some name spaces added, some not used.  Here they are:

Experiment2=4
Experiment3=5
Experiment4=6
CAN=7
Gyro=8

CAN is the CAN commands that you already know about, and are not saved in the diags.  Only experiment 1 is used...3,4,5 and gyro are not.  But there are additional commands in Ops.  I suggest that in the future you test for the max you know about and just put the number in the diag output if you don't know it.  These things are very easy to add, and as you can see, it happens.  Given that we don't publish these much, it is hard to have a spec that you can reliably read.  I'll send you the extra commands separately

**Comment by ac2cz** [comment]
I think I am just going to display the numbers.  Name Space and then Command Number.  e.g.  7:12 for CAN Namespace and command 12.  It's a bit too hard to keep track of and I don't currently have a way for the commands with the same number in the same name space to be different across spacecraft.  So I can't rename Transponder to Health without it changing for Fox-1E or without it being in a different name space. We effectively have different commands but same name space and number.

If that will be hard to debug or too difficult for command stations (who did not write the code) then I could consider adding a config file that contains the data and does the lookup.  Then it could be unique by spacecraft.  We might then only supply the file to command stations.

**Comment by burnsfisher** [comment]
I think that's fine.  Diagnostics are just that.  The command stations are
not likely to use them too often.  It's more for tracing what happened if
the s/c does something weird.  Thanks!

**Comment by burnsfisher** [comment]
This looks good.  Thanks!
