### ISSUE TITLE
Slight change to indicate time check mode in commands

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#559]
The software command count now uses bit 0 (i.e. odd or even ) to say whether reply (time) checking is in effect or not.  In other words, 2 means there has been one software command and replay checking is not in effect, which 3 means there has been one command and replay checking is in effect.  So you can shift the 12-bit count right by 1 to get the actual count.

Not high priority.

**Comment by ac2cz** [comment]
Upgraded to High as this seems important for Husky Sat release which is all in 1.08

**Comment by ac2cz** [comment]
Is this true on Fox-1E as well or just for HuskySat?  

I am assuming it is not the case on Fox-1E but will be true on all LIHU builds going forward.  So I will need a configuration bit in the spacecraft.dat file to know how to decode it for Fox-1E vs others, or I could hard code that this is different just for Fox-1E.

**Comment by burnsfisher** [comment]
Correct, 1E does not have it.

If we are re-working everything for Golf, we could put this in a more
convenient place too.  I don't really like incorporating multiple things
into a single datum.

**Comment by ac2cz** [comment]
I might try breaking this into a 1 bit field and a 15 bit field in the layout. But I seem to remember we had issues with 1 bit fields in the middle of the layout. And we moved them to the ends. 

If splitting into two fields works then it is future proof. Otherwise I like the suggestion to move elsewhere. Then it's just a special case for Husky.

**Comment by ac2cz** [comment]
I need some more clarity on this.  In the intro you say "shift the 12 bit value", but there are 2 separate 6 bit fields for hwCmds and swCmds.  So is it shift the 6 bit value for swCmds?

Or are we talking about the value in the IHU Diagnostic? Rotation number 6 is called COMMAND COUNT and I decode that with an algorithm you supplied.  If there is an ICR attached I use that decode instead.  But this command count is a 16 bit value.  Hence my comment above about 16 bits.  I use the first 8 bits for hw and the last 8 bits for sw.

So are there two different values?  Are they different lengths?  And which has changed for Husky?

More likely I just got confused at some point and coded it wrong.  So let's set it straight for both spacecraft.

**Comment by burnsfisher** [comment]
I should have been more clear.  This is the 32-bit diagnostic word with type=6.  There are 12 bits for each of hw and sw.  Hw can actually count up to 2*12.  However, sw has hijacked bit 0 for the time marker, so it can count up only to 2**11.

My apologies--there was such a small allocation for diagnostic data that it got crammed into a tiny space.  Now we will know better what data wants to be out in the clear and can do better on T.

**Comment by ac2cz** [comment]
Ok, it makes sense now.  And I understand why this is not a separate bit field as it is in the diagnostic.  I'm going to make a special case for Husky.  If this lives beyond Husky we will need a flag or some other method to track that.

**Comment by burnsfisher** [comment]
Where do these come from (the ones in the ICR panel)?  I did not see
anything except the diagnostic.  Do you have the offset in the payload for
me to check?

**Comment by burnsfisher** [comment]
Double oops.  First, I found it.  Never mind the question above.  I put the counts in both places because it started out in diagnostics, but then with the advent of WOD, I wanted the command count in the WOD. And also having some quicker feedback to a command station that the command had been received seemed like a good plan.

But the second oops is that the payload version is just copied from the diagnostic version (and chopped to 6 bits).  So that means that the payload version also has the software command count shifted over by one with bit 0 meaning that timecheck is on.

**Comment by ac2cz** [comment]
Ok, let me implement that for the SW Commands bit field in the payload too.  It will be done in the same way, as a special case for Fox-1E and going forward for anything with an ICR.

**Comment by burnsfisher** [comment]
Not sure just what you mean.  1e does not have the extra time bit.  Only
HuskySat.  We can decide where that info goes in for Golf when we lay out
that telemetry.

**Comment by ac2cz** [comment]
Yes, badly worded by me.  To clarify, the special case is that the ICR on Fox-1E does not have this bit.  It is assumed that future ICRs will set this bit.  No need to move it if the work is done.

**Comment by burnsfisher** [comment]
Ok.  Got it.

**Comment by ac2cz** [comment]
This will be ready to test in 1.08j

**Comment by burnsfisher** [comment]
Ok, it is working fine in 1.08p.  It took a while to remember how to run the whole thing but that was me, not it!
