### ISSUE TITLE
Feature Request:  Button to save properties

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#563]
...or something similar.

I lost about a week of telemetry because my computer rebooted and FoxTelem restarted stopped and without "autostart" checked.  I think I must have set it that way temporarily while doing something or other and then set it back, but did not stop/restart FoxTelem so the properties did not get written.  Oh, and when I restarted it, I did not look again for a couple days--still nothing.  Why?  Same problem, but this time it was because I was in "High Speed" mode.  I remember switching to high speed for a picture taking pass, and again, apparently forgot to restart when I set it back.

**Comment by ac2cz** [comment]
Agree that this is needed.  Automatically Saving when something changes
would also be good. I forget why that was hard and was not implemented
originally.

**Comment by ac2cz** [comment]
This will be in 1.08i
