### ISSUE TITLE
Phasor on/off not initialized correctly

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#566]
If you switch to DUV and back to BPSK, the phasor appears even if it is not checked in "Decoder".  To make it disappear, you have to check it (which makes no change) and then uncheck it (which makes it go away).

**Comment by ac2cz** [comment]
Reproduced in 1.08h.  In fact just stopping and starting the decoder causes it to appear!

**Comment by ac2cz** [comment]
Fixed in 1.08i
