### ISSUE TITLE
User reports unable to change receiver description

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#569]
K4OZS reported the following:

Some time ago Chris mentioned that it would be nice to know which Pi hardware was running FoxTelem.  I recently tried to add this Pi3B+ to my "RF-Receiver Description" info through a VNC connection.  The cursor changes when moved over the dialog box, but I am unable to add info or edit the existing text.

He also reports that stopping and restarting FoxTelem (not rebooting the Pi) fixed the problem.  I asked him to take a screen shot of the setting screen and he took on before and after he restarted FoxTelem. I don't see any differences...

![Capture_FoxTelem_Settings](https://user-images.githubusercontent.com/2413372/64638800-85a19f00-d3d4-11e9-80ff-9b0f994df4c8.JPG)
![Capture_FoxTelem_Settings_2](https://user-images.githubusercontent.com/2413372/64638802-876b6280-d3d4-11e9-836c-a1e23b06eb55.JPG)

**Comment by ac2cz** [comment]
I can't reproduce this.  It seems to work fine over VNC when I test it.  This sounds like a strange VNC/OS/Java VM interaction issue.  I am going to close if we don't have a way to reproduce it.

**Comment by burnsfisher** [comment]
Ok.  Sounds reasonable.
