### ISSUE TITLE
FoxTelem 1.09 Does Not Upload Data

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#570]
FoxTelem 1.09 appears to decode satellite downlinks just fine, and it appears to place the data in the upload queue.  (And then the queue count goes down as though it had been sent).  However, the server never appears to see the data.

I'm marking this critical but probably mainly for release.  I don't know if 1.08 has this problem.

In addition this is only "appears to".  I can't guarantee that this is a problem with FoxTelem, or if the server is somehow rejecting something from 1.09 that really should be legitimate.

**Comment by ac2cz** [comment]
I have reproduced this with 1.08g.  It seems that the STP Date is missing and it gets rejected:
![image](https://user-images.githubusercontent.com/14824793/64660283-a2a69400-d40d-11e9-957c-a454c836dd2d.png)

**Comment by ac2cz** [comment]
I did upload some records earlier, so this might be an issue based on the time of day, or something similar.  This was a high speed record.

**Comment by ac2cz** [comment]
This is fixed in 1.08i and will be in 1.09 when I release that again.

**Comment by burnsfisher** [comment]
Confirmed ok in 1.08n
