### ISSUE TITLE
Linux Add Spacecraft dir selection shows all the spacecraft files

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#587]
This should be limited to show just the .MASTER files if possible.  This is likely also an issue for removing spacecraft.

![image](https://user-images.githubusercontent.com/14824793/66708636-a174c980-ed21-11e9-911e-85d53e649f1f.png)

**Comment by ac2cz** [comment]
If "useNativeFileChooser" is turned to false, then this works on Linux.  Need to work out what the right defaults should be

![image](https://user-images.githubusercontent.com/14824793/66708666-06c8ba80-ed22-11e9-9e75-afee9de2a606.png)

**Comment by ac2cz** [comment]
This has got into a bit of a mess.  useNativeFileChooser is forced off for the initial settings on Linux, otherwise you can't choose a dir.  BUT it is NOT foced off for the log files dir selection on the settings window.  

There is still an option for "useNativeFileChooser" but this should default to false for linux as initial start.  true for windows I think.

**Comment by ac2cz** [comment]
By default Windows and Mac use the native file chooser.  Linux is now set by default not to.
In the DIR Chooser flow Windows is forced to use the NON native file chooser as the native DIR chooser does not work
In the Spacecraft file add/remove flow Linux is forced to the NON native file chooser as the filter does not work.  For Wav file load it will follow what the user picks.

**Comment by ac2cz** [comment]
Actually the Linux Dir Chooser has the same issue as windows and needs to be disallowed

**Comment by burnsfisher** [comment]
Whew!  What a mess!  In any case, the HuskySat directory still shows in the chooser, but it does correctly limit the other files to the correct ones and I was able to find and select HuskySat.

I'll reassign back to Chris, but if you think this is not important feel free to close it.

**Comment by burnsfisher** [comment]
Should there actually BE a HuskySat directory in the Spacecraft directory from the distribution?  HuskySat is the only one that actually has a directory there.  Maybe that's why it is showing?

**Comment by ac2cz** [comment]
I'll consider renaming the "HuskySat" directory.  It contains all of the CAN Packet layouts and it is a lot, so I did not want to just dump them all into the spacecraft directory.  It is needed for any spacecraft that sends CAN Packets down to earth, so hopefully just Husky!

If it was named "UW Can Packet Layouts" then would that make it clear that it can be ignored?

**Comment by burnsfisher** [comment]
It's probably not that important.  It just looks a bit odd being there when
you are asked to add a satellite.  I would not spend a lot of time on it.

**Comment by ac2cz** [comment]
I'm going to close this then.   I don't want to make a change that might break something for UW.  If we decide it is confusing enough later than I will fix in a later release.
