### ISSUE TITLE
Crash in 1.08n

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#594]
The attached crash dialog box was on my system when I returned from Symposium.  It appears as though it might only be affecting a single satellite (AO-85) given that all the others are still producing data.  Of course it might be that AO-85 is not sending telemetry when it passes over me and that crash happened within minutes of when I looked.

<img width="1045" alt="Screen Shot 2019-10-22 at 1 21 44 PM" src="https://user-images.githubusercontent.com/2413372/67312688-c14d7f80-f4cf-11e9-8ae0-21ddecab1818.png">

**Comment by burnsfisher** [comment]
Forgot to say that the data screen showing is AO-85, so it has not been updated since 10/17.  And the data base implies that I have not sent any AO-85 telemetry recently either.  And I'm also attaching a picture of the Input page settings.  Unfortunately, no tracing enabled.
<img width="1038" alt="Screen Shot 2019-10-22 at 1 30 36 PM" src="https://user-images.githubusercontent.com/2413372/67313044-4e90d400-f4d0-11e9-802a-12891e5d8ffd.png">

**Comment by ac2cz** [comment]
This is a crash that should not happen.  I suspect that we have a corrupt frame and the type was wrong.  Currently I default to Type 1 but I have decided that is an error and I should throw the frame away.

Can you look for the file FOX1A_rttelemetryFM.csv and paste it here or send it to me?  It should be in the directory where the jar file is and in the spacecraft subdirectory.

**Comment by ac2cz** [comment]
I have implemented some defensive code to prevent this error.

**Comment by burnsfisher** [comment]
Sent by email since github does not allow a csv file to be attached.

**Comment by burnsfisher** [comment]
But I'm going to close this until and unless I get another one.  That csv file may not contain anything useful.
