### ISSUE TITLE
FoxTelem 1.08o appears to have messed with properties directory location

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#595]
1.08n was running ok on the Pi4 (except for #594).  I then ran 1.08o and it could not install any of the new spacecraft files.  Why?  Because the directory it was trying to install them to did not exist.  It looks like it changed the properties directory.  I then went back to running 1.08n and it had the same problem trying to access the same incorrect directory.

I'll try to reproduce and get more info, but here is a screen shot of the problem:

<img width="934" alt="Screen Shot 2019-10-22 at 1 40 36 PM" src="https://user-images.githubusercontent.com/2413372/67314240-5b162c00-f4d2-11e9-81cb-ce8b24ce0672.png">

**Comment by burnsfisher** [comment]
Ok, I manually fixed the ~/.FoxTelem properties file to have the correct directory and I was able to run both 1.08o and 1.08n.  But the difference is that starting 1.08o did to give me the message about the properties file format changing and should I let it fix that for me.  So I infer that the messup happened when it updated the properties file.

**Comment by burnsfisher** [comment]
In the process of all this, it also lost the name of the groundstation and some of the check boxes in the properties page relating to tracking (like doppler correction).

**Comment by ac2cz** [comment]
I can't reproduce this, you will have to give me more details.  

If I run 1.07n without passing it a logfile_dir on the command line, so it is using the central ~/.FoxTelem properties, and then "upgrade" to 1.08o and run, then there is no message.  It just opens fine.

If you have the "format change" message at first launch then you are upgrading from an earlier version than 1.08n.  Is it possible that you have previously used a launch script and usually the properties are in the logfile directory?  When you ran it without a launch script it will run against the central settings.  Could they have been from 1.07 and pointing to a logfile dir that does not exist anymore?  In which case the error message would be correct.  It's hard to know how else to handle it.

**Comment by burnsfisher** [comment]
Ok, I think this is totally my screwup.  It's been so long since this just did not work I forgot some important stuff, like using the right script.  Let's just ignore it.
