### ISSUE TITLE
9700 seems to be getting low decodes after upgrade to 1.08

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#598]
ver 1.08 yesterday, and now I can’t collect any telemetry. I see a good ‘eye’ pattern, but 0 decodes

**Comment by sjkps** [comment]
A 9700 USB IF output produces 2 images/humps on the FFT display, 1.07y would decode from either image, 1.08 has to be on the right hand side image to decode.

**Comment by ac2cz** [comment]
It's possible that is happening. Thanks for the feedback.

I have reproduced the issue in the lab, though I don't have the two
signals. I've coded a fix and will make it available shortly.

**Comment by sjkps** [comment]
try this as a audio source from a 9700 and you will see the humps https://www.dropbox.com/s/eh5bya72y8gfskt/fox1.wav?dl=0

**Comment by ac2cz** [comment]
Thanks for the recording.  I agree that both humps decode on 1.07 and only the right hand hump decodes in 1.08.  This is separate to the issue I reproduced with Find Signal and fixed.  I will investigate further.

**Comment by ac2cz** [comment]
I think I have fixed this.

You can patch your 1.08 release by replacing the jar file with this test version:
https://www.g0kla.com/foxtelem/downloads/test/FoxTelem.jar

**Comment by sjkps** [comment]
It will be later tonight before I get a live pass but the new jar works with my wav files on both sides that  was not working before.  Thanks Chris.
