### ISSUE TITLE
Line Unavailable Exception on PC with 1.08w

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#605]
I've just left this running and not paid much attention.  This error was showing this morning, although the decoder seemed to be running.  I'm including a screen shot of the error and a screen shot of part of the log so you can see the timestamp.  Then I'll also include the log itself.
<img width="867" alt="Screen Shot 2019-12-09 at 8 44 03 AM" src="https://user-images.githubusercontent.com/2413372/70441003-77a9fb80-1a61-11ea-8f9e-6f4231cc060a.png">
<img width="392" alt="Screen Shot 2019-12-09 at 8 49 50 AM" src="https://user-images.githubusercontent.com/2413372/70441016-80023680-1a61-11ea-8728-a82a96af9b35.png">
[FoxTelemDecoder20191206.log](https://github.com/ac2cz/FoxTelem/files/3939951/FoxTelemDecoder20191206.log)

**Comment by burnsfisher** [comment]
Ha...well I did not notice that it was right at the end of the log.  That 2nd screen shot was not really required :-)

**Comment by ac2cz** [comment]
I will keep this open and try to improve the error message.

**Comment by ac2cz** [comment]
I have improved the error messages in 1.09k and I am going to close this.
