### ISSUE TITLE
Array out of bounds on Eye panel on "old" 1.08w.

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#606]
When I went to my PC to replace the old 1.08w with the new one I found this present waiting for me.  I'm including a screen shot and the log.
<img width="863" alt="Screen Shot 2019-12-12 at 6 46 05 PM" src="https://user-images.githubusercontent.com/2413372/70758298-89fd9100-1d10-11ea-80a8-6617fa059441.png">
[FoxTelemDecoder20191212.log](https://github.com/ac2cz/FoxTelem/files/3958276/FoxTelemDecoder20191212.log)

**Comment by ac2cz** [comment]
That's too funny.  That is the bug that I fixed between 1.08w 6 Dec and 12 Dec !  Run the new version and let me know if you see it again.  Hopefully I fixed it.  I'll leave this open and we will come back and close it if we don't see it again.

**Comment by burnsfisher** [comment]
The new one is running now

**Comment by ac2cz** [comment]
Ok, I'm closing this as no new reports
