### ISSUE TITLE
Error with Decimation Rate on RTL-SDR

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#609]
From Ed Krome, K9EK 

I know that the use of RTL-SDR with FIAB is considered a bit flaky, but I'm doing it anyway. Kinda works; typically gets 30% as many frames as the 2 sets of "normal" (FCDP+ w/ RP3B+) on the same antenna. But what I do often get is "error with decimation rate" box "try stopping and restarting". That usually works, but I have had to reboot to get it to clear. But things seem to continue working even if I don't stop/restart. This is new since I updated to 1.08w on this RP4 w/4Gb. Any ideas? 
(BTW I'm running 1.08w on all 3 units)

**Comment by burnsfisher** [comment]
A note from Ed when I asked him how often it happened:

All the time. Except when it doesn't feel like it. At this moment it is functioning properly. A few minutes ago the "decimation error-try stopping and restarting" boxes appeared and would not close no matter how may times I agreed with it or hit the X. FT was locked up, I finally rebooted the RP4. At this moment it is working (I am watching it by VNC or a second computer). Problem does not appear related to whether I an watching the input screen or not. At this moment it is decoding AO91; 11 frames but the RP3+FCD pair has decoded 30 in the same time. The RTL is in raised cosine.
BTW: I mentioned I am running 2 identical RP3B+ with FCDP+ off a splitter. (The RTL is off of the same splitter). One of those 2 is running Raised Cosine (512 samples), the other Windowed sync (480 filter length). The raised cosine is a bit better today but sometimes windowed sync is better.

**Comment by ac2cz** [comment]
I fixed this in 1.08z4

**Comment by burnsfisher** [comment]
Great news.  I'll check with Ed as soon as z4 (or later) is released and if it solves his problem, I'll close this.

**Comment by ac2cz** [comment]
Need to test if this is really fixed and close it

**Comment by burnsfisher** [comment]
Ok, apparently I never send the promised mail to Ed.  I have done so now, and will close this when he reports.  If he does not, I suggest closing it.

**Comment by burnsfisher** [comment]
Ed says he has not seen that error at all in 1.08z5.  Closing...
