### ISSUE TITLE
Auto band switch only works with FoxTelem Doppler

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#614]
Mark or Alan was having good luck using "find signal" rather than "FoxTelem Calculates Doppler" so I tried that.  The problem is that auto band and mode switching does not work in this configuration. 
 "FoxTelem Calculates Position" is checked, and auto-start when above horizon works.  Only auto band and mode switching does NOT without FoxTelem doppler.

**Comment by ac2cz** [comment]
I think I fixed this at some point.  

In 1.09k if "Find Signal" is checked AND you check "Auto Start" then "Auto Switch Modes" becomes available.  You need to check "Auto Start" because otherwise all of the spacecraft are being checked continually.  That is the classic "Find Signal" scheme.  If that was allowed it causes the Decoder to switch bands and modes every 100mS, which does not work with a hardware device in the chain.

**Comment by burnsfisher** [comment]
Thanks...I did not get a chance (read *forgot*) to check this before.  I'm running it now on n3.

**Comment by burnsfisher** [comment]
HuskySat just appeared (obviously no downlink) and yes, it switched to BPSK:Fox/Husky, but it did not switch bands.  It stayed on 2M.  I do have Autostart, Auto Switch Mode checked on the input tab, and FoxTelem Calculates Position and Find Signal checked on the preferences panel.  This is 1.09n3.

**Comment by ac2cz** [comment]
Ok, then let's keep this open and see what is going on.

**Comment by ac2cz** [comment]
Let me just clarify though.  It says "Auto Switch Mode" and it did do that.  It does not say "Auto Switch Mode / Retune Center" or whatever the message is.  So the retune part is locked out.  Is this in the situation where you are using the IC-9700?

Here in a PI it is setup to Retune.  I can confirm that you have to have Retune Doppler on for that to work:
![image](https://user-images.githubusercontent.com/14824793/100940043-4671d900-34c5-11eb-8a01-da90b01d35f8.png)

**Comment by burnsfisher** [comment]
Correct, that is what it says.   It does not say "retune center".  However,
I am not doing the 9700 IF thing.  This is just a funcube dongle in a
Raspberry Pi.

**Comment by burnsfisher** [comment]
A bit more looking.  Yes, it only specifies choose a center frequency if I
have "FoxTelem Calculates Doppler".  I can understand how this might work
algorithmically, but it is only somewhat useful.  I expected it to switch
to the band of the satellite that it calculated was AOS and then search for
the signal in that band (possibly starting at the nominal frequency).

As I recall, HuskySat was so fussy about getting tuned in well that it
worked best with FindSignal, but most people don't have the ability to run
a different copy and a different FCD for each band.
