### ISSUE TITLE
costas  dp selection lost on autoswitch

### ISSUE THREAD

**Issue by sjkps** [ac2cz/FoxTelem#617]
Would like the ability to stay in dp  through autoswitches,  right now I can select dp for a pass but is lost as autoswitch jumps through different sats and comes back to husky it goes back to costas.  thanks

**Comment by ac2cz** [comment]
Go to the spacecraft menu and open the spacecraft options window.  At the top right under "Frequency and Tracking" is a mode.  Pull down the list and select BPSK 1200 (Dot Prod).  Now when it switches it will default to the Dot Prod.  You can pick any of the decoders you like for any of the spacecraft.

**Comment by sjkps** [comment]
Well let me apologize for missing that and bugging you! I see it now.  Thanks for the quick reply.
