### ISSUE TITLE
FoxTelem 1.08z5 crash

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#626]
<img width="828" alt="Screen Shot 2020-03-22 at 9 34 49 AM" src="https://user-images.githubusercontent.com/2413372/77250939-b71be280-6c21-11ea-8731-404ef3477429.png">

Nothing much I can say about it except that it was on a Windows system, and logging and debug frames was turned on with nothing really interesting in the log.  I can get it to you if you want though.

Suggestion:  Putting the time in an error box might be helpful

**Comment by ac2cz** [comment]
I think this is fixed in 1.09.  Let me know if you see it there.

**Comment by burnsfisher** [comment]
I've seen a similar message (null exception), but it is probably not the same.  (I sent you and email).  Will keep you posted.

**Comment by ac2cz** [comment]
I've added some more defensive code and an error message as this is related to the soft coded frame layouts we are using.  Those are in 1.09k3.  I will leave this marked as fixed.

**Comment by burnsfisher** [comment]
I have not seen this in a long time
