### ISSUE TITLE
Odd satellite priority behavior

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#627]
Today AO-92 was going to be doing pictures.  I changed AO-92 so it had priority 1 (In the Spacecraft menu).  AO-91 has priority 2.  The first pass when I was watching it seemed to do as expected, although they did not overlap.  AO-91 came by first.  Then AO-92 came by in DUV mode.  After the camera was switched on, it started displaying the high-speed decode.  

On some other later pass when I was not watching, I will guess that they DID overlap with AO-91 coming first.  Notice the screen shot.  This was taken after it was all over.  You can see that the demodulate bar is set over AO-91, and yet there is the clear signature of a picture downlink at the high end of the AO-92 frequency, which would be early in the pass.  So it appears to me that FoxTelem stopped at the end of AO-91 and never switched to AO-92.  I would have expected that it would switch to AO-92 as soon at AO-92 was AOS.

BTW, AO-91 is set to use DUV only, while AO-92 is set to DUV + HS.  I'm not sure if that is significant.  This is obviously difficult to reproduce.

![Screenshot from 2020-04-28 15-56-24](https://user-images.githubusercontent.com/2413372/80532169-b9343800-8969-11ea-8617-62f2ce02ca8c.png)

**Comment by burnsfisher** [comment]
I noticed something else this morning:  HuskySat was actually AOS when I happened to look--it showed red on the 'tracking' panel, but the decoder was not running.  I unchecked "AutoStart" and noticed that the "Start" button thought it was started.  I pushed it to stop and then pushed again to run it.  It ran for maybe 10 or 15 seconds and then stopped.

I restarted FoxTelem...same behavior.  Then I rebooted the PC (which required updates).  By the time it was rebooted, I was LOS, but I started the decoder manually anyway, and it did not stop after a minute or so.  Thus: 

a) This seems like it might relate to or be the same as the the first issue
b) I don't know whether Windows updates related to this, or Windows just needed a reboot (what a you-know-what).  
c) It could also be that I could not reproduce it because the satellite was LOS and the problem is still there.  But what started the problem?  (b) seems most likely to me, but then again I love to hate Windows :-)

**Comment by ac2cz** [comment]
Hey Burns, in the first screenshot, I see the 9600bps signal from AO-92, but whatever keps you are using show that AO-92 was at -67 degrees elevation. It is printed in the top right.  So FoxTelem is not going to start decoding. Could the name be wrong in the settings and your keps are out of date?

**Comment by burnsfisher** [comment]
Chris, yes, this screen shot was taken long after the pass.  FoxTelem is correct that AO-92 is not visible.  What you should note is that the decoder is STOPPED because there are no satellites visible, and that the demodulation bars are showing AO-91. You can backtrack the orbit from now if you like, but I'm pretty sure that on this pass, AO-91 was up first, then AO-92.  And it appears to me that it never switched to demodulating AO-92, but (and I'm guessing here) it stopped the decoder when AO-91 went LOS and 92 was still up high.

**Comment by ac2cz** [comment]
I will try to reproduce this. I don't suppose you know the date/time of the
pass?

**Comment by burnsfisher** [comment]
I'm reasonably sure it was April 28 around 1615UTC.

**Comment by ac2cz** [comment]
Ok, I tried this.  I see the pass you mean.  I set AO-91 as Priority 2 and AO-92 as Priority 1.  The passes overlap as you say, but AO-91 is first and then AO-92.

**Comment by burnsfisher** [comment]
Yes.  So my hunch was that since 91 was first, FoxTelem started tracking
it, but did not switch when AO-92 came up.  Of course it all could be
related to that other problem I reported that seemed to get fixed on Java
upgrade and reboot.

**Comment by ac2cz** [comment]
Ok, I am going to close this as not re-producible.  We can re-open if we see it again and have an error message to chase.
