### ISSUE TITLE
Error scaling graph size

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#641]
In 1.09L

![image](https://user-images.githubusercontent.com/14824793/87841199-a1d26000-c871-11ea-9a3e-84ad314adb93.png)

**Comment by josepharmbruster** [comment]
@ac2cz  - Can you provide specific steps that can be used to reproduce this?

**Comment by ac2cz** [comment]
It's possible that this was fixed.  It was likely shrinking the graph window to the absolute minimum size.

**Comment by josepharmbruster** [comment]
I've tried a bunch of different operations; minimizing / maximizing, alternating the size, with no luck... I am guessing it could also be related to a specific set of data providing a specific value to getUtcTimeForReset (from the looks of the stack trace).

**Comment by ac2cz** [comment]
Ok, I will close this as not reproducible.
