### ISSUE TITLE
Conversion curve comments can not have commas

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#648]
I am adding 3 conversion curves in 1.09l, and I found that 1 worked, while the other 2 did not (the raw values were displayed regardless of the raw value checkbox).  The three curves are as follows:

8_bit_accel | -2 | 0.015625 | 0 | 0 | 0 | 0 | Gs (range=+/- 2)
8_bit_mag | -76.8 | 0.6 | 0 | 0 | 0 | 0 | Microteslas, range = ~ +/- 76.8
8_bit_spin | -3.9 | 0.0305 | 0 | 0 | 0 | 0 | Degrees per second, range=about +/- 46  a should be 3.

Only 8_bit_accel works.  The other two work if I remove the comments (actually replace them with the accel comment.  They all have odd characters.  Perhaps it is the length? I'll experiment, but I wanted to note this immediately.

**Comment by burnsfisher** [comment]
I found the problem:  You can't have a comma in the comment--since this is a CSV file, that make a new column.  I'll leave this at low priority in case you want to allow additional columns (that do nothing) to avoid this.  But if not, I'm ok if you want to close it.

**Comment by ac2cz** [comment]
Ah, yes.  Comma is forbidden.  It's actually a difficult one to avoid.  We could use a different separator but then that will cause an issue if used.  But perhaps a tab would be better and more unlikely in the comment field.  Or I could allow an escape for commas if we think they should be supported.

**Comment by burnsfisher** [comment]
It's not critical.  If you can possibly pick it out it would be nice to give a clearer message, but feel free to close this if you want.

**Comment by burnsfisher** [comment]
I say "clearer" message.  I think that it gave no message at all, actually.

**Comment by burnsfisher** [comment]
Just reading this again.  Of course a comma just adds another column.  You must ignore comments in these files anyway.  Can you just convince Java to ignore any number of columns beyond the one you want?  Again, not really critical.

**Comment by ac2cz** [comment]
I have changed this to read the comment up to any comma.  It then ignores comments after that.  This has the slightly dangerous side effect that a comma earlier in the file will cause a bad conversion to be loaded, but with no error message.

This is in 1.09m

**Comment by burnsfisher** [comment]
Oh, I see.  You are saying that a good side effect of the problem that I mentioned is that there is some chance that it will give an error if you have left out something.  Hmm.  I think I agree with this fix given that the good side effect only would work for certain cases, while a comma in a comment is a vary useful delimiter.  Thanks!
