### ISSUE TITLE
Missing USB Device on Raspberry Pi with RTL-SDR

### ISSUE THREAD

**Issue by DH1OK** [ac2cz/FoxTelem#674]
Hello,
I didn't find something about my issue in the net, so I think i ask for help here. 
I build on my Raspberry Pi a new Raspian OS (buster) on the SD card and installed all the rtl-sdr drivers needed. After that I make the test (rtl_test -t) and the USB-Stick is working fine and i can control everything via gqrx. 

So I thought the next step is to install FoxTelem (1.09) The installation was fine but after the selection of the Audio-Source and pressing the "Start" button I got a message "Missing USB device" . Does anybody knows why?

![Screenshot 2021-01-17 183206](https://user-images.githubusercontent.com/29518831/104850959-59642f80-58f2-11eb-86ce-d93413d5c435.jpg)

Thanks for help
Olaf

**Comment by ac2cz** [comment]
Thanks for the report.  Only some RTL devices are supported.  There are many different manufacturers.  Can you give some details on the RTL you are using?

**Comment by DH1OK** [comment]
Hello
my RTL-Stick is a No-Name DVB-T+FM+DAB Stick. LSUSB says:
Bus 001 Device 004: ID 0bda:2832 Realtek Semiconductor Corp. RTL2832U DVB-T

But this is not the only RTL-Stick i have here in my shack. So I used another one and this throws me an error:

![Screenshot 2021-01-18 082408](https://user-images.githubusercontent.com/29518831/104884380-8b16de00-5966-11eb-8971-8c60bde0a738.jpg)

And also my third device didn''t work:

Bus 001 Device 004: ID 1d19:1101 Dexatek Technology Ltd. DK DVB-T Dongle


Olaf

**Comment by ac2cz** [comment]
The E4000 tuner is not yet supported in the production code, but as you can see from #638 I have a build that might work with that tuner.  You can download Version 1.10c here: https://www.g0kla.com/foxtelem/downloads/test/
Let me know if that works.

The Dexatek Dongle is not supported.  It has Vendor/Product Id 1d19 and 1101.  I am only looking for 0bda & 2832 and then I only support the R802T and experimentally, the E4000 tuners.

**Comment by DH1OK** [comment]
Hello Chris,

nice to hear this from you. So ok I will try the 1.10 version and write down my experience soon. thanks for the help.

Olaf

**Comment by DH1OK** [comment]
Hello Chris,

the new version 1.10c now detects the E4000 Tuner RTL-Stick. But when I press the "Start" button appears another error:

![Screenshot 2021-01-21 194003](https://user-images.githubusercontent.com/29518831/105396971-c93f2680-5c20-11eb-875f-da8460b57f17.jpg)

And it doesn't matter what frequency i put in the center frequency filed (145920.0 or 145940.0). But it seems to me the reception of the signals will go anyway. Well i try to receive the Data today in the afternoon.

Olaf

**Comment by ac2cz** [comment]
See issue #638 for an update.

**Comment by DH1OK** [comment]
Hello Chris,

I can also confirm that the messages disappeared. it seems to me that everything is going right now. Thanks for the help
