### ISSUE TITLE
instructions on how to compile

### ISSUE THREAD

**Issue by DC7IA** [ac2cz/FoxTelem#678]
I cannot find any instructions on how to compile FoxTelem. Please provide some instructions.

**Comment by ac2cz** [comment]
Instructions on how to build are here: https://www.g0kla.com/foxtelem/build_foxtelem.php

I did them a while ago.  Let me know if anything does not work and needs to be updated.  

Feel free to ask questions if you need help.  My main motivation is to help people learn about satellites, amateur radio, DSP and coding.  So always happy to answer questions.

**Comment by ac2cz** [comment]
I added these instructions to the readme for the repo.  So I will close this.
