### ISSUE TITLE
More hard-to-understand error messages when changing layouts

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#700]
![Screenshot 2021-09-01 12 49 44](https://user-images.githubusercontent.com/2413372/131712033-10f360cd-fbaf-4362-bc14-47aaeadb8b7b.png)

Note that this message says nothing about the column or row or even which panel.  It is also misleading in that column E in the CSV file (the units) commonly has - in it if we don't want a unit.  This is often a problem too if we have nothing there.  But in fact, this appears to have happened because column K (the thing that seems to say whether it has a matching min/max or not) was blank rather than 0 (and it did not have "-" in it.

Don't get me wrong--it is amazing that I can make these changes, and it does not have to be super user-friendly.  However, useful error messages would be a big improvement and hopefully not too hard.

**Comment by ac2cz** [comment]
Yes, agree this should give better information about the location of the issue.

**Comment by ac2cz** [comment]
Version 1.12k will show the row and column of the layout that caused the error.  Let me know any other obscure error messages.
