### ISSUE TITLE
Time conversion requested

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#709]
I know---you just close a bunch and I put in a new one :-)

Anyway, it would be nice (low priority) to have a time conversion.  Input would have to be two fields (epoch and seconds) and the conversion would print either  epoch/seconds or UTC time (depending on raw or not raw, or maybe UTC or not UTC).   I don't know if two inputs is possible.  I guess an alternative it might have a 40-whatever bit field that had both epoch and seconds).

**Comment by ac2cz** [comment]
Can you give me some more details?  Is this connected to the GPS time?  Or is this a separate timestamp?  Is this the same as the T0 conversion or a different conversion?

**Comment by burnsfisher** [comment]
Not directly connected to the GPS time.  There are now several timestamps downlinked, including the min/max reset times, min last change time, max last change time, and maybe a few others.  Right now those appear on two separate lines in a panel: Epoch and Seconds.  It would be easier to read if the appeared together:  27/37584 for example.  And if UTC (or not raw) was checked, it would use the T0 time to display in UTC.  Actually, it probably would be more consistent that 27/37548 (or whatever) would appear as "raw" and a 23:44:51 would appear if not raw was checked.  And UTC would switch the non-raw version between local and UTC.  But don't go nuts :-)  Just UTC or x/y would be better than we have now.

**Comment by ac2cz** [comment]
Upping the priority of this because I think it is desired and I almost never filter for Low Priority.

**Comment by ac2cz** [comment]
Error checking added on 1.12p to handle missing or incorrect arguments to the TIMESTAMP function.

**Comment by burnsfisher** [comment]
One issue that I can see on 1.12o (assign back to me if this is fixed with the changes you made):  A panel that I placed in the "Partner WOD" tab which uses this time does epoch/seconds ok, but does not do UTC even with UTC checked.  (On the health tab it works ok).

**Comment by burnsfisher** [comment]
Assigned to Chris for issue above.

**Comment by ac2cz** [comment]
Ok, I need to look at that.  It should follow the UTC checkbox.

**Comment by burnsfisher** [comment]
The time conversion works ok in the health WOD tab.  I'm about to request a pull that will have the changes that show this (and also fix the health WOD tab which currently only shows 4 panels!)

**Comment by ac2cz** [comment]
I reproduced the issue where the UTC checkbox does not switch from time to epoch / uptime on the Partner WOD tag.   It is fixed in 1.12p.

**Comment by burnsfisher** [comment]
Thanks!
