### ISSUE TITLE
Something odd happening with Health WOD when we return to earlier data

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#722]
A bit hard to describe, and I'm not 100% sure it is FoxTelem or flight software.  But I don't see any of this when I print it out from flight.

As you know, the flight software stores WOD into a circular buffer.  If there were 4 records in the buffer, we would download 1,2,3,4,1,2,3,4,1,2,4 and when a 5th one is added, we add it to the list:  1,2,3,4,1,2,3,4,1,2,3,4,5,1,2,3,4,5 etc.  When the buffer flips around early in flight like this (before the buffer is totally full) the index number order is also the time order.  1 is the older, 5 is the newest in this case.

What appears to be happening is that approximately when the buffer flips back to the start, FoxTelem records an illegal record time and then continues on.  Here is what I see on the debug printout of the flight software:
**Returning WOD epoch 9, secs 1505, next index is 23
Returning WOD epoch 9, secs 1569, next index is 24
Returning WOD epoch 9, secs 1633, next index is 25
Returning WOD epoch 9, secs 1697, next index is 26
Returning WOD epoch 9, secs 1761, next index is 27
Returning WOD epoch 9, secs 1825, next index is 28
Returning WOD epoch 9, secs 1889, next index is 29
Returning WOD epoch 9, secs 1953, next index is 30
Returning WOD epoch 9, secs 2017, next index is 31
Returning WOD epoch 9, secs 2081, next index is 32
Returning WOD epoch 9, secs 97, next index is 1
Returning WOD epoch 9, secs 161, next index is 2
Returning WOD epoch 9, secs 225, next index is 3**
 And the screenshot is what shows up on the FoxTelem output (the first record appeared immediately after 9/97 appeared)

![Screenshot 2021-11-18 11 30 03](https://user-images.githubusercontent.com/2413372/142456254-b1901f38-ff6d-4520-931a-2b9a1591e3bf.png)
![Screenshot 2021-11-18 11 33 54](https://user-images.githubusercontent.com/2413372/142457090-e52c9e23-cac4-41ff-9dbd-9558a3db61a0.png)

 
The log does show the illegal record (another screen shot...this may well be from earlier before I cleared the data to show the telemetry more clearly.

I'll do my best to get you a telemetry recording.

**Comment by ac2cz** [comment]
From the data above it looks like the frame received at epoch 9 uptime 1973 contains 3 WOD records.  Those WOD records are for:
9 / 1825
9/ 1889
255 / -1526726647

The frame might be corrupted but still passed the RS Decoder.  We have seen that before.  But it does pass the CRC check.  It also looks like the suspect WOD record is corrupt while the rest of the frame is not.  Meaning it has the corrupt timestamp fields but almost all the rest of the fields are 0. This is in contrast to the other WOD records.  So I think we have to assume that the frame overall was valid. 

It's hard to think of a bug at my end .If I was off by a byte then we would get corrupted values throughout.  

Is it possible that the WOD record was not populated?  That is is effectively empty.  If it happens at the end of the cycle, then could you fail to add the third record if only two were available?

**Comment by burnsfisher** [comment]
Hmm.  Thank you.  Can you tell me what the frame type is (by number is fine).  

As you can see, I printed out each payload as I filled it, and they were ok.  I guess what I need to do is to mark them frame by frame, and look again after they are placed in the frame.  As you say, it is hard to imagine what is going on.  It should just go back to the beginning of the ring buffer to get the next one.

**Comment by ac2cz** [comment]
It was a type 7 frame.  

And the frame it sends straight after is a type 2 frame but it in fact has the last WOD record with uptime 1953, followed by the first one of the cycle with uptime 97.

Another thing to note.  When it tries to save the record with epoch 255 and uptime -1526726647 it says it is a DUPLICATE (or corrupt) and is not saved.  It says that for all the WOD records in that frame.  I know it is not flagged as corrupt by FoxTelem  because I print out more debug info for corrupt records, so it is a duplicate.  That suggests that FoxTelem has received it more than once.  Which further suggests that it was transmitted and was being sent each time the buffer wrapped around.  Of course FoxTelem could be mangling it in the same way each time for some reason, but I can't think what that would be..

**Comment by burnsfisher** [comment]
Ok, thanks.  Yes, the duplicate stuff is not surprising since it is going round and round.  But the fact that the bad payload is repeated is very interesting.  I just managed to reproduce it after only a few seconds and stopped everything so I can look at the log on both ends and try to compare them.  Thanks for the help.  I'll let you know what I see.

**Comment by burnsfisher** [comment]
Thanks for all the help.  In one sense the problem WAS in FoxTelem, but it was still my bug.  I had not updated the Frame7 definition to match what I was sending down in Frame 7.  So all the CRCs worked; it was just interpreting a couple things wrong :-)

I'll give you a pull with the fix shortly.

**Comment by burnsfisher** [comment]
Appears to be fine with the pull.  Thanks!
