### ISSUE TITLE
Could not write properies file if change too fast

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#735]
Very minor bug:  If you check (or uncheck) "Display Raw Values" and then uncheck (or re-check) quickly, you often get an error message "Could not write properties file".  I suspect this is just because it is trying to write it again while it is still open or perhaps there are two threads both trying to write at the same time.

Very minor but confusing for anyone not familiar with how these things work.  I suppose it would be true with other properties, but I have not tried it.

This is on 1.12s, but I have not tried any earlier.

**Comment by burnsfisher** [comment]
Oh, and "Ok" does not always dismiss the message.  The "X" on the window does.

**Comment by ac2cz** [comment]
I can't reproduce this.  Can you give me any more details?  Was this on Windows or Linux or Mac?  I clicked continuously on Ubuntu without issue.

**Comment by burnsfisher** [comment]
I've totally forgotten about this, and have not seen it lately.  Give it was 12s, probably on Windows.  But if you can't repro it, might as well close it.

**Comment by ac2cz** [comment]
Ok, no problem.  To be sure I tried this on Windows too.  But it was fine.  So perhaps something strange was going on and the file was locked by something else.  I will close.
