### ISSUE TITLE
We should sort the fields in the ComboBox that allows another graph trace to be added

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#740]
Sorting the list of names is trivial, but we also need to sort the list of field names stored in variables.  Or we need a new mechanism to retrieve the fieldname from the pick in the combo box.

**Comment by ac2cz** [comment]
This is fixed in 1.12w1 or later

**Comment by burnsfisher** [comment]
I'll add the very minor complaint that + and - are sorted.  So for example +X Panel is actually first while a librarian might expect it to be nearly last.  But no problem for me :-)  I'm happy with it!  Thank you!
