### ISSUE TITLE
Right hand Graph scale does not show String Lookup table values

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#741]
From Burns:
​While Ok and Fail text is shows if you graph the heartbeat first, if you add it second so the "scale" is on the right, the scale is numerical rather than text.

**Comment by ac2cz** [comment]
This will be in v1.12w1 or later.

Note that in testing this I noticed that two different String lookup tables do not work because they both have the same "units".  To make this work you could give the Lookup tables units of some kind, but then that would be visible on the display.

**Comment by burnsfisher** [comment]
Ok, it works.  Thanks!
